HDMI_DIR = ../intel_media/otm_hdmi


obj-$(CONFIG_DRM_MRFLD) += drv/
obj-$(CONFIG_DRM_MRFLD) += ../intel_media/video/common/
obj-$(CONFIG_DRM_MRFLD) += ../intel_media/video/decode/
obj-$(CONFIG_DRM_MRFLD) += ../intel_media/video/encode/
obj-$(CONFIG_SUPPORT_VSP) += ../intel_media/video/vsp/
obj-$(CONFIG_MRFL_DISPLAY) += fbdrv/
obj-$(CONFIG_DRM_MRFLD)	   += rgx/

obj-$(CONFIG_SUPPORT_HDMI) += $(HDMI_DIR)/
