obj-$(CONFIG_DRM_MRFLD) += drv/
obj-$(CONFIG_DRM_MRFLD) += ../intel_media/video/common/
obj-$(CONFIG_DRM_MRFLD) += ../intel_media/video/decode/
#obj-$(CONFIG_DRM_MRFLD) += vsp/
obj-$(CONFIG_MRFL_DISPLAY) += fbdrv/
obj-$(CONFIG_DRM_MRFLD)	   += rgx/

obj-$(CONFIG_SUPPORT_HDMI) += drv/otm_hdmi/
