#
# Makefile for industrial I/O Magnetometer sensors
#

obj-$(CONFIG_SENSORS_AK8975)	+= ak8975.o
obj-$(CONFIG_SENSORS_HMC5843)	+= hmc5843.o

#<ASUS-GUC20130730+>
obj-y += inv_compass/
#<ASUS-GUC20130730->