ccflags-y += -DATOMISP_POSTFIX=\"css2400_v2\" -DCONFIG_ISP2400 -DCONFIG_VIDEO_ATOMISP_CSS20
CONFIG_VIDEO_ATOMISP_CSS20 := m
CONFIG_ISP2400 := y
postfix := css2400_v2

include $(srctree)/$(src)/../Makefile.common
