EXTRA_CFLAGS += -Idrivers/staging/intel_media/common \
			-Idrivers/staging/mrst/drv \
			-Idrivers/staging/mrst/drv/otm_hdmi/os/android/include \
			-Idrivers/staging/mrst/drv/otm_hdmi/pil/include

obj-$(CONFIG_SUPPORT_HDMI)	+= intel_mid_had.o
intel_mid_had-objs := intel_mid_hdmi_audio.o intel_mid_hdmi_audio_if.o
