EXTRA_CFLAGS += -Idrivers/staging/mrst/drv \
	        -Idrivers/staging/mrst/drv/otm_hdmi/os/android/include

obj-$(CONFIG_SND_INTELMID_HDMI_AUDIO)	+= intel_mid_had.o
intel_mid_had-objs := intel_mid_hdmi_audio.o intel_mid_hdmi_audio_if.o
