obj-$(CONFIG_HID_NTRIG_G4)		+= ntrig-common.o ntrig-dispatcher.o ntrig-dispatcher-sysfs.o ntrig-ncp-driver.o ntrig-dispatcher-sys-depend-android.o ntrig-direct-event-driver.o
obj-$(CONFIG_NTRIG_SPI_G4)		+= ntrig_spi.o ntrig_low_msg.o
