#ifndef __MRFL_DISPLAY_CONTROLLER_H
#define __MRFL_DISPLAY_CONTROLLER_H

#define MRFL_FB_HACT		480
#define MRFL_FB_VACT		800
#define MRFL_FB_RGB888		0x4
#define MRFL_FB_RGB565		0x1
#define MRFL_FB_PCI_FB_BASE	0x5C
#define MRFL_FB_CMAP_LEN	16
#define MRFL_FB_YPAN_STEP	1
#define MRFL_FB_BPP		16
#define MRFL_FB_RED_OFS		11
#define MRFL_FB_RED_LEN		5
#define MRFL_FB_GREEN_OFS	5
#define MRFL_FB_GREEN_LEN	6
#define MRFL_FB_BLUE_OFS	0
#define MRFL_FB_BLUE_LEN	5
#define MRFL_FB_PIXMAP_SIZE	4096
#define MRFL_FB_PIXMAP_BALIGN	4
#define MRFL_FB_PIXMAP_SALIGN	1
#define MRFL_FB_PIXMAP_AALIGN	32
#define MRFL_FB_CMAP_ALLOC_LEN	256

#endif

