/*
 * Support for Medfield PNW Camera Imaging ISP subsystem.
 *
 * Copyright (c) 2010 Intel Corporation. All Rights Reserved.
 *
 * Copyright (c) 2010 Silicon Hive www.siliconhive.com.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version
 * 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 *
 */

#ifndef _hive_isp_css_2400_system_hrtx_h_hrt_
#define _hive_isp_css_2400_system_hrtx_h_hrt_

//#include <hrt/expert_api.h>

#include <scalar_processor_2400_cell_hrtx.h>
#include <isp2400_mamoiada_cell_hrtx.h>

enum hrt_hive_processors {
  testbench_isp_isp = 0,
  testbench_isp_scp = 1,
  hrt_num_hive_processors = 2
};
enum hrt_host_processors {
  host = 0,
  hrt_num_host_processors = 1
};
enum hrt_system_memories {
  testbench_ddram = 0,
  testbench_ddram_small = 1,
  testbench_isp_inp_sys_input_buffer = 2,
  hrt_num_system_memories = 3
};
enum hrt_fifo_adapters {
  testbench_isp_fa_sp_isp = 0,
  testbench_isp_inp_sys_fifo_adapter = 1,
  testbench_isp_isel_fa = 2,
  hrt_num_fifo_adapters = 3
};
enum hrt_fifos {
  hrt_num_fifos = 0
};
enum hrt_system_busses {
  i_host_bus = 0,
  testbench_wide_bus = 1,
  testbench_isp_vec_bus = 2,
  testbench_isp_data_bus = 3,
  testbench_isp_host_bus = 4,
  testbench_isp_inp_sys_wide_bus = 5,
  testbench_isp_inp_sys_ctrl_bus = 6,
  testbench_isp_isel_isel_bus = 7,
  testbench_isp_ifmt_ctrl_bus = 8,
  testbench_isp_gpd_gp_bus = 9,
  testbench_isp_nar_bus_pnbus = 10,
  testbench_isp_nar_bus_nbus = 11,
  testbench_isp_slv_grp_bus_sgp_bus = 12,
  testbench_isp_out_sys_sec_data_bus = 13,
  testbench_system_bus_cio_bus = 14,
  hrt_num_system_busses = 15
};
enum hrt_bridges {
  testbench_tb_ocp2cio = 5,
  testbench_sm2wide = 7,
  testbench_wide_ce = 8,
  testbench_ddram_staller = 9,
  testbench_wide_ce_2 = 10,
  testbench_isp_ift_sec_pipe = 12,
  testbench_isp_cio_subword_conv = 15,
  testbench_isp_vec_bus_pipe = 16,
  testbench_isp_cio_conv_vamem = 17,
  testbench_isp_cio_conv_isp = 18,
  testbench_isp_scp_pipe = 44,
  testbench_isp_cio_conv_sp = 45,
  testbench_isp_ocp2cio_nar_bus = 46,
  testbench_isp_data_bus_pipe = 47,
  testbench_isp_inp_sys_cio2ahb = 56,
  testbench_isp_inp_sys_cio_conv = 82,
  testbench_isp_ifmt_pifa_pipe = 105,
  testbench_isp_ifmt_pifb_pipe = 106,
  testbench_isp_nar_bus_ift_sec_pipe = 120,
  testbench_isp_nar_bus_mem_cpy_pipe = 121,
  testbench_isp_nar_bus_gpd_pipe = 122,
  testbench_isp_nar_bus_dma_pipe = 123,
  testbench_isp_nar_bus_pn_bus_pipe = 124,
  testbench_isp_nar_bus_isp_dmem_slv_pipe = 125,
  testbench_isp_nar_bus_slv_grp_slv_pipe = 126,
  testbench_isp_nar_bus_scp_slv_pipe = 127,
  testbench_isp_slv_grp_bus_mmu_slv_pipe = 128,
  testbench_isp_slv_grp_bus_dma_slv_pipe = 129,
  testbench_isp_slv_grp_bus_isys_slv_pipe = 130,
  testbench_isp_slv_grp_bus_vamem_slv_pipe = 131,
  testbench_isp_out_sys_at_req_pipe = 133,
  testbench_isp_out_sys_cio_conv_mmu = 135,
  testbench_isp_out_sys_cio2ocp_wide_data_out = 136,
  testbench_system_bus_tb_cio2ocp = 137,
  hrt_num_bridges = 34
};
enum hrt_custom_devices {
  recorder = 0,
  player = 1,
  testbench_sig_mon = 2,
  testbench_sensor = 3,
  testbench_gp_adapter = 4,
  testbench_master_rec = 6,
  testbench_jtag_gpr = 11,
  testbench_isp_gdc1 = 13,
  testbench_isp_gdc2 = 14,
  testbench_isp_isp_dma = 19,
  testbench_isp_sf_isp2sp = 20,
  testbench_isp_sf_sp2isp = 21,
  testbench_isp_sf_cells2pifa = 22,
  testbench_isp_sf_pifa2cells = 23,
  testbench_isp_sf_cells2pifb = 24,
  testbench_isp_sf_pifb2cells = 25,
  testbench_isp_sf_sp2sif = 26,
  testbench_isp_sf_sif2sp = 27,
  testbench_isp_sf_sp2mc = 28,
  testbench_isp_sf_mc2sp = 29,
  testbench_isp_sf_sp2inpsys = 30,
  testbench_isp_sf_inpsys2sp = 31,
  testbench_isp_sf_isp2dma = 32,
  testbench_isp_sf_dma2isp = 33,
  testbench_isp_sf_sp2dma = 34,
  testbench_isp_sf_dma2sp = 35,
  testbench_isp_sf_cells2gdc = 36,
  testbench_isp_sf_gdc2cells = 37,
  testbench_isp_sf_cells2gdc2 = 38,
  testbench_isp_sf_gdc22cells = 39,
  testbench_isp_SPStrMon = 40,
  testbench_isp_SPStrMon_B = 41,
  testbench_isp_ISPStrMon = 42,
  testbench_isp_ModStrMon = 43,
  testbench_isp_sf_sp2fa = 48,
  testbench_isp_sf_fa2sp = 49,
  testbench_isp_sf_isp2fa = 50,
  testbench_isp_sf_fa2isp = 51,
  testbench_isp_tck_inverter = 52,
  testbench_isp_jtag2cio = 53,
  testbench_isp_inp_sys_csi_receiver = 54,
  testbench_isp_inp_sys_px_str_deint = 55,
  testbench_isp_inp_sys_sf_strmon2strmc_a = 57,
  testbench_isp_inp_sys_sf_strmon2strmc_b = 58,
  testbench_isp_inp_sys_sf_strmon2strmc_c = 59,
  testbench_isp_inp_sys_stream_multicast_a = 60,
  testbench_isp_inp_sys_stream_multicast_b = 61,
  testbench_isp_inp_sys_stream_multicast_c = 62,
  testbench_isp_inp_sys_stream_mux = 63,
  testbench_isp_inp_sys_capt_unit_a = 64,
  testbench_isp_inp_sys_capt_unit_b = 65,
  testbench_isp_inp_sys_capt_unit_c = 66,
  testbench_isp_inp_sys_acq_unit = 67,
  testbench_isp_inp_sys_inp_ctrl = 68,
  testbench_isp_inp_sys_dma = 69,
  testbench_isp_inp_sys_sf_ctrl2capta = 70,
  testbench_isp_inp_sys_sf_capta2ctrl = 71,
  testbench_isp_inp_sys_sf_ctrl2captb = 72,
  testbench_isp_inp_sys_sf_captb2ctrl = 73,
  testbench_isp_inp_sys_sf_ctrl2captc = 74,
  testbench_isp_inp_sys_sf_captc2ctrl = 75,
  testbench_isp_inp_sys_sf_ctrl2acq = 76,
  testbench_isp_inp_sys_sf_acq2ctrl = 77,
  testbench_isp_inp_sys_sf_csi2adptr = 78,
  testbench_isp_inp_sys_csi_str_mon = 79,
  testbench_isp_inp_sys_gpreg = 80,
  testbench_isp_inp_sys_irq_ctrl = 81,
  testbench_isp_isel_gpr = 83,
  testbench_isp_isel_irq_ctrl = 84,
  testbench_isp_isel_sync_gen = 85,
  testbench_isp_isel_i_prbs = 86,
  testbench_isp_isel_tpg = 87,
  testbench_isp_isel_sf_fa = 88,
  testbench_isp_isel_str2mipi = 89,
  testbench_isp_isel_st_mux = 90,
  testbench_isp_isel_st_mux_b = 91,
  testbench_isp_isel_sol_mux = 92,
  testbench_isp_isel_eol_mux = 93,
  testbench_isp_isel_sof_mux = 94,
  testbench_isp_isel_eof_mux = 95,
  testbench_isp_isel_fmt_mux = 96,
  testbench_isp_isel_chid_mux = 97,
  testbench_isp_ifmt_inp_sw = 98,
  testbench_isp_ifmt_ift_prim = 99,
  testbench_isp_ifmt_ift_prim_b = 100,
  testbench_isp_ifmt_ift_sec = 101,
  testbench_isp_ifmt_mem_cpy = 102,
  testbench_isp_ifmt_gp_reg = 103,
  testbench_isp_ifmt_irq_ctrl = 104,
  testbench_isp_ifa_sw_mux = 107,
  testbench_isp_ifa_sw_demux = 108,
  testbench_isp_ifb_sw_mux = 109,
  testbench_isp_ifb_sw_demux = 110,
  testbench_isp_gdc1_sw_mux = 111,
  testbench_isp_gdc1_sw_demux = 112,
  testbench_isp_gdc2_sw_mux = 113,
  testbench_isp_gdc2_sw_demux = 114,
  testbench_isp_gpd_c_gpio = 115,
  testbench_isp_gpd_tc = 116,
  testbench_isp_gpd_gptimer = 117,
  testbench_isp_gpd_irq_ctrl = 118,
  testbench_isp_gpd_gp_reg = 119,
  testbench_isp_out_sys_addr_trans = 132,
  testbench_isp_out_sys_c_mmu = 134,
  hrt_num_custom_devices = 104
};
enum hrt_slave_ports {
  recorder_sl,
  i_host_bus_host_in,
  i_host_bus_bfm_play_in,
  testbench_sig_mon_slv_in,
  testbench_gp_adapter_slv_in,
  testbench_master_rec_sl,
  testbench_wide_bus_host_in,
  testbench_wide_bus_isp_in,
  testbench_ddram_ip0,
  testbench_ddram_small_ip0,
  testbench_jtag_gpr_slv_in,
  testbench_isp_gdc1_sl_in,
  testbench_isp_gdc2_sl_in,
  testbench_isp_vec_bus_vec0_in,
  testbench_isp_vec_bus_vec1_in,
  testbench_isp_vec_bus_vec2_in,
  testbench_isp_vec_bus_vec3_in,
  testbench_isp_vec_bus_vec4_in,
  testbench_isp_vec_bus_vec5_in,
  testbench_isp_isp_sl_ipstatctrl,
  testbench_isp_isp_sl_ipdmem,
  testbench_isp_isp_sl_ippmem,
  testbench_isp_isp_sl_ipvamem,
  testbench_isp_isp_sl_iphist,
  testbench_isp_isp_simd_ipdma,
  testbench_isp_isp_dma_ctrl,
  testbench_isp_scp_sl_ip0,
  testbench_isp_scp_sl_ip1,
  testbench_isp_data_bus_isp_dma_in,
  testbench_isp_data_bus_scp_in,
  testbench_isp_data_bus_isp_in,
  testbench_isp_data_bus_inp_sys_dma_in,
  testbench_isp_fa_sp_isp_sl_in,
  testbench_isp_host_bus_system_in,
  testbench_isp_inp_sys_csi_receiver_ctrl_in,
  testbench_isp_inp_sys_csi_receiver_ctrl_be_in,
  testbench_isp_inp_sys_capt_unit_a_control_in,
  testbench_isp_inp_sys_capt_unit_b_control_in,
  testbench_isp_inp_sys_capt_unit_c_control_in,
  testbench_isp_inp_sys_acq_unit_control_in,
  testbench_isp_inp_sys_inp_ctrl_slv,
  testbench_isp_inp_sys_dma_ctrl_sl,
  testbench_isp_inp_sys_fifo_adapter_slv_in,
  testbench_isp_inp_sys_gpreg_slv_in,
  testbench_isp_inp_sys_irq_ctrl_slv_in,
  testbench_isp_inp_sys_wide_bus_slv0_capt_a,
  testbench_isp_inp_sys_wide_bus_slv1_capt_b,
  testbench_isp_inp_sys_wide_bus_slv2_capt_c,
  testbench_isp_inp_sys_wide_bus_slv3_acq,
  testbench_isp_inp_sys_wide_bus_slv4_dma,
  testbench_isp_inp_sys_wide_bus_slv5_ctrl_bus,
  testbench_isp_inp_sys_ctrl_bus_slv_ctrl,
  testbench_isp_inp_sys_input_buffer_ip0,
  testbench_isp_isel_isel_bus_system_in,
  testbench_isp_isel_gpr_slv_in,
  testbench_isp_isel_irq_ctrl_slv_in,
  testbench_isp_isel_fa_sl_in,
  testbench_isp_ifmt_ift_prim_sl_in,
  testbench_isp_ifmt_ift_prim_b_sl_in,
  testbench_isp_ifmt_ift_sec_sl_in,
  testbench_isp_ifmt_mem_cpy_sl_in,
  testbench_isp_ifmt_gp_reg_slv_in,
  testbench_isp_ifmt_irq_ctrl_slv_in,
  testbench_isp_ifmt_ctrl_bus_ctrl_in,
  testbench_isp_gpd_gp_bus_system_in,
  testbench_isp_gpd_c_gpio_ctrl_in,
  testbench_isp_gpd_tc_slv_in,
  testbench_isp_gpd_gptimer_slv_in,
  testbench_isp_gpd_irq_ctrl_slv_in,
  testbench_isp_gpd_gp_reg_slv_in,
  testbench_isp_nar_bus_pnbus_ift_sec_in,
  testbench_isp_nar_bus_pnbus_mem_cpy_in,
  testbench_isp_nar_bus_pnbus_gpd_in,
  testbench_isp_nar_bus_nbus_system_in,
  testbench_isp_nar_bus_nbus_scp_in,
  testbench_isp_nar_bus_nbus_pre_nrr_in,
  testbench_isp_nar_bus_nbus_dma_in,
  testbench_isp_slv_grp_bus_sgp_bus_cfg_bus_in,
  testbench_isp_out_sys_addr_trans_in,
  testbench_isp_out_sys_c_mmu_ctrl_in,
  testbench_isp_out_sys_c_mmu_request_in,
  testbench_isp_out_sys_sec_data_bus_address_trans_in,
  testbench_isp_out_sys_sec_data_bus_mmu_in,
  testbench_system_bus_cio_bus_host_in,
  testbench_tb_ocp2cio_sl,
  testbench_sm2wide_sl,
  testbench_wide_ce_sl,
  testbench_ddram_staller_sl,
  testbench_wide_ce_2_sl,
  testbench_isp_ift_sec_pipe_sl,
  testbench_isp_cio_subword_conv_sl,
  testbench_isp_vec_bus_pipe_sl,
  testbench_isp_cio_conv_vamem_sl,
  testbench_isp_cio_conv_isp_sl,
  testbench_isp_scp_pipe_sl,
  testbench_isp_cio_conv_sp_sl,
  testbench_isp_ocp2cio_nar_bus_sl,
  testbench_isp_data_bus_pipe_sl,
  testbench_isp_inp_sys_cio2ahb_sl,
  testbench_isp_inp_sys_cio_conv_sl,
  testbench_isp_ifmt_pifa_pipe_sl,
  testbench_isp_ifmt_pifb_pipe_sl,
  testbench_isp_nar_bus_ift_sec_pipe_sl,
  testbench_isp_nar_bus_mem_cpy_pipe_sl,
  testbench_isp_nar_bus_gpd_pipe_sl,
  testbench_isp_nar_bus_dma_pipe_sl,
  testbench_isp_nar_bus_pn_bus_pipe_sl,
  testbench_isp_nar_bus_isp_dmem_slv_pipe_sl,
  testbench_isp_nar_bus_slv_grp_slv_pipe_sl,
  testbench_isp_nar_bus_scp_slv_pipe_sl,
  testbench_isp_slv_grp_bus_mmu_slv_pipe_sl,
  testbench_isp_slv_grp_bus_dma_slv_pipe_sl,
  testbench_isp_slv_grp_bus_isys_slv_pipe_sl,
  testbench_isp_slv_grp_bus_vamem_slv_pipe_sl,
  testbench_isp_out_sys_at_req_pipe_sl,
  testbench_isp_out_sys_cio_conv_mmu_sl,
  testbench_isp_out_sys_cio2ocp_wide_data_out_sl,
  testbench_system_bus_tb_cio2ocp_sl,
  hrt_num_slave_ports
};
enum hrt_stream_in_ports {
  testbench_isp_gdc1_st_cmd_in,
  testbench_isp_gdc2_st_cmd_in,
  testbench_isp_isp_st_ipif,
  testbench_isp_isp_st_ipif_b,
  testbench_isp_isp_st_ipdma,
  testbench_isp_isp_st_ipgdc,
  testbench_isp_isp_st_ipscl,
  testbench_isp_isp_st_ipgpfifo,
  testbench_isp_isp_st_ipsp,
  testbench_isp_isp_dma_cmd0,
  testbench_isp_isp_dma_cmd1,
  testbench_isp_sf_isp2sp_in,
  testbench_isp_sf_sp2isp_in,
  testbench_isp_sf_cells2pifa_in,
  testbench_isp_sf_pifa2cells_in,
  testbench_isp_sf_cells2pifb_in,
  testbench_isp_sf_pifb2cells_in,
  testbench_isp_sf_sp2sif_in,
  testbench_isp_sf_sif2sp_in,
  testbench_isp_sf_sp2mc_in,
  testbench_isp_sf_mc2sp_in,
  testbench_isp_sf_sp2inpsys_in,
  testbench_isp_sf_inpsys2sp_in,
  testbench_isp_sf_isp2dma_in,
  testbench_isp_sf_dma2isp_in,
  testbench_isp_sf_sp2dma_in,
  testbench_isp_sf_dma2sp_in,
  testbench_isp_sf_cells2gdc_in,
  testbench_isp_sf_gdc2cells_in,
  testbench_isp_sf_cells2gdc2_in,
  testbench_isp_sf_gdc22cells_in,
  testbench_isp_SPStrMon_in0,
  testbench_isp_SPStrMon_in1,
  testbench_isp_SPStrMon_in2,
  testbench_isp_SPStrMon_in3,
  testbench_isp_SPStrMon_in4,
  testbench_isp_SPStrMon_in5,
  testbench_isp_SPStrMon_in6,
  testbench_isp_SPStrMon_in7,
  testbench_isp_SPStrMon_in8,
  testbench_isp_SPStrMon_in9,
  testbench_isp_SPStrMon_in10,
  testbench_isp_SPStrMon_in11,
  testbench_isp_SPStrMon_in12,
  testbench_isp_SPStrMon_in13,
  testbench_isp_SPStrMon_in14,
  testbench_isp_SPStrMon_in15,
  testbench_isp_SPStrMon_B_in0,
  testbench_isp_SPStrMon_B_in1,
  testbench_isp_SPStrMon_B_in2,
  testbench_isp_SPStrMon_B_in3,
  testbench_isp_ISPStrMon_in0,
  testbench_isp_ISPStrMon_in1,
  testbench_isp_ISPStrMon_in2,
  testbench_isp_ISPStrMon_in3,
  testbench_isp_ISPStrMon_in4,
  testbench_isp_ISPStrMon_in5,
  testbench_isp_ISPStrMon_in6,
  testbench_isp_ISPStrMon_in7,
  testbench_isp_ISPStrMon_in8,
  testbench_isp_ISPStrMon_in9,
  testbench_isp_ISPStrMon_in10,
  testbench_isp_ISPStrMon_in11,
  testbench_isp_ISPStrMon_in12,
  testbench_isp_ISPStrMon_in13,
  testbench_isp_ModStrMon_in0,
  testbench_isp_ModStrMon_in1,
  testbench_isp_ModStrMon_in2,
  testbench_isp_ModStrMon_in3,
  testbench_isp_ModStrMon_in4,
  testbench_isp_ModStrMon_in5,
  testbench_isp_ModStrMon_in6,
  testbench_isp_ModStrMon_in7,
  testbench_isp_ModStrMon_in8,
  testbench_isp_ModStrMon_in9,
  testbench_isp_ModStrMon_in10,
  testbench_isp_ModStrMon_in11,
  testbench_isp_ModStrMon_in12,
  testbench_isp_ModStrMon_in13,
  testbench_isp_ModStrMon_in14,
  testbench_isp_ModStrMon_in15,
  testbench_isp_scp_st_ip0,
  testbench_isp_scp_st_ip1,
  testbench_isp_scp_st_ip2,
  testbench_isp_scp_st_ip3,
  testbench_isp_scp_st_ip4,
  testbench_isp_scp_st_ip5,
  testbench_isp_scp_st_ip6,
  testbench_isp_scp_st_ip7,
  testbench_isp_scp_st_ip8,
  testbench_isp_scp_st_ip9,
  testbench_isp_scp_st_ip10,
  testbench_isp_fa_sp_isp_st_sp_in,
  testbench_isp_fa_sp_isp_st_isp_in,
  testbench_isp_sf_sp2fa_in,
  testbench_isp_sf_fa2sp_in,
  testbench_isp_sf_isp2fa_in,
  testbench_isp_sf_fa2isp_in,
  testbench_isp_inp_sys_csi_receiver_acq_data_in,
  testbench_isp_inp_sys_px_str_deint_str_in_0,
  testbench_isp_inp_sys_px_str_deint_str_in_1,
  testbench_isp_inp_sys_sf_strmon2strmc_a_in,
  testbench_isp_inp_sys_sf_strmon2strmc_b_in,
  testbench_isp_inp_sys_sf_strmon2strmc_c_in,
  testbench_isp_inp_sys_stream_multicast_a_st_in,
  testbench_isp_inp_sys_stream_multicast_b_st_in,
  testbench_isp_inp_sys_stream_multicast_c_st_in,
  testbench_isp_inp_sys_stream_mux_st_in_0,
  testbench_isp_inp_sys_stream_mux_st_in_1,
  testbench_isp_inp_sys_stream_mux_st_in_2,
  testbench_isp_inp_sys_stream_mux_st_in_3,
  testbench_isp_inp_sys_capt_unit_a_data_in,
  testbench_isp_inp_sys_capt_unit_a_command_in,
  testbench_isp_inp_sys_capt_unit_b_data_in,
  testbench_isp_inp_sys_capt_unit_b_command_in,
  testbench_isp_inp_sys_capt_unit_c_data_in,
  testbench_isp_inp_sys_capt_unit_c_command_in,
  testbench_isp_inp_sys_acq_unit_command_in,
  testbench_isp_inp_sys_inp_ctrl_ctrl_cmd,
  testbench_isp_inp_sys_inp_ctrl_capta_ack,
  testbench_isp_inp_sys_inp_ctrl_captb_ack,
  testbench_isp_inp_sys_inp_ctrl_captc_ack,
  testbench_isp_inp_sys_inp_ctrl_acq_ack,
  testbench_isp_inp_sys_inp_ctrl_dma_capta_ack,
  testbench_isp_inp_sys_inp_ctrl_dma_captb_ack,
  testbench_isp_inp_sys_inp_ctrl_dma_captc_ack,
  testbench_isp_inp_sys_inp_ctrl_dma_acq_ack,
  testbench_isp_inp_sys_dma_ctrl_cmd0,
  testbench_isp_inp_sys_dma_ctrl_cmd1,
  testbench_isp_inp_sys_dma_ctrl_cmd2,
  testbench_isp_inp_sys_dma_ctrl_cmd3,
  testbench_isp_inp_sys_sf_ctrl2capta_in,
  testbench_isp_inp_sys_sf_capta2ctrl_in,
  testbench_isp_inp_sys_sf_ctrl2captb_in,
  testbench_isp_inp_sys_sf_captb2ctrl_in,
  testbench_isp_inp_sys_sf_ctrl2captc_in,
  testbench_isp_inp_sys_sf_captc2ctrl_in,
  testbench_isp_inp_sys_sf_ctrl2acq_in,
  testbench_isp_inp_sys_sf_acq2ctrl_in,
  testbench_isp_inp_sys_sf_csi2adptr_in,
  testbench_isp_inp_sys_fifo_adapter_st_in,
  testbench_isp_inp_sys_csi_str_mon_capa_in,
  testbench_isp_inp_sys_csi_str_mon_capb_in,
  testbench_isp_inp_sys_csi_str_mon_capc_in,
  testbench_isp_inp_sys_csi_str_mon_acq_in,
  testbench_isp_inp_sys_csi_str_mon_css_gensh_in,
  testbench_isp_inp_sys_csi_str_mon_fa_gensh_in,
  testbench_isp_inp_sys_csi_str_mon_sp_cmd_in,
  testbench_isp_inp_sys_csi_str_mon_sp_ack_in,
  testbench_isp_inp_sys_csi_str_mon_css_pixa_in,
  testbench_isp_inp_sys_csi_str_mon_css_pixb_in,
  testbench_isp_inp_sys_csi_str_mon_px_str_deint_0_in,
  testbench_isp_inp_sys_csi_str_mon_px_str_deint_1_in,
  testbench_isp_isel_sf_fa_in,
  testbench_isp_isel_str2mipi_st_data_in,
  testbench_isp_isel_st_mux_st_mipi_data_in,
  testbench_isp_isel_st_mux_st_prbs_data_in,
  testbench_isp_isel_st_mux_st_pat_gen_data_in,
  testbench_isp_isel_st_mux_st_str2mipi_data_in,
  testbench_isp_isel_st_mux_b_st_mipi_data_in,
  testbench_isp_isel_st_mux_b_st_prbs_data_in,
  testbench_isp_isel_st_mux_b_st_pat_gen_data_in,
  testbench_isp_isel_st_mux_b_st_str2mipi_data_in,
  testbench_isp_ifmt_inp_sw_st_data_in,
  testbench_isp_ifmt_inp_sw_st_data_b_in,
  testbench_isp_ifmt_ift_prim_st_sync_in,
  testbench_isp_ifmt_ift_prim_st_data_in,
  testbench_isp_ifmt_ift_prim_b_st_sync_in,
  testbench_isp_ifmt_ift_prim_b_st_data_in,
  testbench_isp_ifmt_ift_sec_st_sync_in,
  testbench_isp_ifmt_ift_sec_st_data_in,
  testbench_isp_ifmt_mem_cpy_st_sync_in,
  testbench_isp_ifmt_mem_cpy_st_data_in,
  testbench_isp_ifmt_mem_cpy_st_data_b_in,
  testbench_isp_ifa_sw_mux_sta_in,
  testbench_isp_ifa_sw_mux_stb_in,
  testbench_isp_ifa_sw_demux_st_in,
  testbench_isp_ifb_sw_mux_sta_in,
  testbench_isp_ifb_sw_mux_stb_in,
  testbench_isp_ifb_sw_demux_st_in,
  testbench_isp_gdc1_sw_mux_sta_in,
  testbench_isp_gdc1_sw_mux_stb_in,
  testbench_isp_gdc1_sw_demux_st_in,
  testbench_isp_gdc2_sw_mux_sta_in,
  testbench_isp_gdc2_sw_mux_stb_in,
  testbench_isp_gdc2_sw_demux_st_in,
  hrt_num_stream_in_ports
};
enum hrt_stream_out_ports {
  testbench_isp_gdc1_st_ack_out,
  testbench_isp_gdc2_st_ack_out,
  testbench_isp_isp_st_opif,
  testbench_isp_isp_st_opif_b,
  testbench_isp_isp_st_opdma,
  testbench_isp_isp_st_opgdc,
  testbench_isp_isp_st_opscl,
  testbench_isp_isp_st_opgpfifo,
  testbench_isp_isp_st_opsp,
  testbench_isp_isp_dma_ack_port0,
  testbench_isp_isp_dma_ack_port1,
  testbench_isp_sf_isp2sp_out,
  testbench_isp_sf_sp2isp_out,
  testbench_isp_sf_cells2pifa_out,
  testbench_isp_sf_pifa2cells_out,
  testbench_isp_sf_cells2pifb_out,
  testbench_isp_sf_pifb2cells_out,
  testbench_isp_sf_sp2sif_out,
  testbench_isp_sf_sif2sp_out,
  testbench_isp_sf_sp2mc_out,
  testbench_isp_sf_mc2sp_out,
  testbench_isp_sf_sp2inpsys_out,
  testbench_isp_sf_inpsys2sp_out,
  testbench_isp_sf_isp2dma_out,
  testbench_isp_sf_dma2isp_out,
  testbench_isp_sf_sp2dma_out,
  testbench_isp_sf_dma2sp_out,
  testbench_isp_sf_cells2gdc_out,
  testbench_isp_sf_gdc2cells_out,
  testbench_isp_sf_cells2gdc2_out,
  testbench_isp_sf_gdc22cells_out,
  testbench_isp_SPStrMon_out0,
  testbench_isp_SPStrMon_out1,
  testbench_isp_SPStrMon_out2,
  testbench_isp_SPStrMon_out3,
  testbench_isp_SPStrMon_out4,
  testbench_isp_SPStrMon_out5,
  testbench_isp_SPStrMon_out6,
  testbench_isp_SPStrMon_out7,
  testbench_isp_SPStrMon_out8,
  testbench_isp_SPStrMon_out9,
  testbench_isp_SPStrMon_out10,
  testbench_isp_SPStrMon_out11,
  testbench_isp_SPStrMon_out12,
  testbench_isp_SPStrMon_out13,
  testbench_isp_SPStrMon_out14,
  testbench_isp_SPStrMon_out15,
  testbench_isp_SPStrMon_B_out0,
  testbench_isp_SPStrMon_B_out1,
  testbench_isp_SPStrMon_B_out2,
  testbench_isp_SPStrMon_B_out3,
  testbench_isp_ISPStrMon_out0,
  testbench_isp_ISPStrMon_out1,
  testbench_isp_ISPStrMon_out2,
  testbench_isp_ISPStrMon_out3,
  testbench_isp_ISPStrMon_out4,
  testbench_isp_ISPStrMon_out5,
  testbench_isp_ISPStrMon_out6,
  testbench_isp_ISPStrMon_out7,
  testbench_isp_ISPStrMon_out8,
  testbench_isp_ISPStrMon_out9,
  testbench_isp_ISPStrMon_out10,
  testbench_isp_ISPStrMon_out11,
  testbench_isp_ISPStrMon_out12,
  testbench_isp_ISPStrMon_out13,
  testbench_isp_ModStrMon_out0,
  testbench_isp_ModStrMon_out1,
  testbench_isp_ModStrMon_out2,
  testbench_isp_ModStrMon_out3,
  testbench_isp_ModStrMon_out4,
  testbench_isp_ModStrMon_out5,
  testbench_isp_ModStrMon_out6,
  testbench_isp_ModStrMon_out7,
  testbench_isp_ModStrMon_out8,
  testbench_isp_ModStrMon_out9,
  testbench_isp_ModStrMon_out10,
  testbench_isp_ModStrMon_out11,
  testbench_isp_ModStrMon_out12,
  testbench_isp_ModStrMon_out13,
  testbench_isp_ModStrMon_out14,
  testbench_isp_ModStrMon_out15,
  testbench_isp_scp_st_op0,
  testbench_isp_scp_st_op1,
  testbench_isp_scp_st_op2,
  testbench_isp_scp_st_op3,
  testbench_isp_scp_st_op4,
  testbench_isp_scp_st_op5,
  testbench_isp_scp_st_op6,
  testbench_isp_scp_st_op7,
  testbench_isp_scp_st_op8,
  testbench_isp_scp_st_op9,
  testbench_isp_scp_st_op10,
  testbench_isp_fa_sp_isp_st_sp_out,
  testbench_isp_fa_sp_isp_st_isp_out,
  testbench_isp_sf_sp2fa_out,
  testbench_isp_sf_fa2sp_out,
  testbench_isp_sf_isp2fa_out,
  testbench_isp_sf_fa2isp_out,
  testbench_isp_inp_sys_csi_receiver_capa_data_out,
  testbench_isp_inp_sys_csi_receiver_capb_data_out,
  testbench_isp_inp_sys_csi_receiver_capc_data_out,
  testbench_isp_inp_sys_csi_receiver_px_data_out,
  testbench_isp_inp_sys_csi_receiver_px_data_b_out,
  testbench_isp_inp_sys_csi_receiver_gen_short_str_out,
  testbench_isp_inp_sys_px_str_deint_str_out_0,
  testbench_isp_inp_sys_px_str_deint_str_out_1,
  testbench_isp_inp_sys_sf_strmon2strmc_a_out,
  testbench_isp_inp_sys_sf_strmon2strmc_b_out,
  testbench_isp_inp_sys_sf_strmon2strmc_c_out,
  testbench_isp_inp_sys_stream_multicast_a_st_out_0,
  testbench_isp_inp_sys_stream_multicast_a_st_out_1,
  testbench_isp_inp_sys_stream_multicast_b_st_out_0,
  testbench_isp_inp_sys_stream_multicast_b_st_out_1,
  testbench_isp_inp_sys_stream_multicast_c_st_out_0,
  testbench_isp_inp_sys_stream_multicast_c_st_out_1,
  testbench_isp_inp_sys_stream_mux_st_out,
  testbench_isp_inp_sys_capt_unit_a_ack_out,
  testbench_isp_inp_sys_capt_unit_b_ack_out,
  testbench_isp_inp_sys_capt_unit_c_ack_out,
  testbench_isp_inp_sys_acq_unit_data_out,
  testbench_isp_inp_sys_acq_unit_ack_out,
  testbench_isp_inp_sys_inp_ctrl_ctrl_ack,
  testbench_isp_inp_sys_inp_ctrl_capta_cmd,
  testbench_isp_inp_sys_inp_ctrl_captb_cmd,
  testbench_isp_inp_sys_inp_ctrl_captc_cmd,
  testbench_isp_inp_sys_inp_ctrl_acq_cmd,
  testbench_isp_inp_sys_inp_ctrl_dma_capta_cmd,
  testbench_isp_inp_sys_inp_ctrl_dma_captb_cmd,
  testbench_isp_inp_sys_inp_ctrl_dma_captc_cmd,
  testbench_isp_inp_sys_inp_ctrl_dma_acq_cmd,
  testbench_isp_inp_sys_dma_ctrl_ack0,
  testbench_isp_inp_sys_dma_ctrl_ack1,
  testbench_isp_inp_sys_dma_ctrl_ack2,
  testbench_isp_inp_sys_dma_ctrl_ack3,
  testbench_isp_inp_sys_sf_ctrl2capta_out,
  testbench_isp_inp_sys_sf_capta2ctrl_out,
  testbench_isp_inp_sys_sf_ctrl2captb_out,
  testbench_isp_inp_sys_sf_captb2ctrl_out,
  testbench_isp_inp_sys_sf_ctrl2captc_out,
  testbench_isp_inp_sys_sf_captc2ctrl_out,
  testbench_isp_inp_sys_sf_ctrl2acq_out,
  testbench_isp_inp_sys_sf_acq2ctrl_out,
  testbench_isp_inp_sys_sf_csi2adptr_out,
  testbench_isp_inp_sys_csi_str_mon_capa_out,
  testbench_isp_inp_sys_csi_str_mon_capb_out,
  testbench_isp_inp_sys_csi_str_mon_capc_out,
  testbench_isp_inp_sys_csi_str_mon_acq_out,
  testbench_isp_inp_sys_csi_str_mon_css_gensh_out,
  testbench_isp_inp_sys_csi_str_mon_fa_gensh_out,
  testbench_isp_inp_sys_csi_str_mon_sp_cmd_out,
  testbench_isp_inp_sys_csi_str_mon_sp_ack_out,
  testbench_isp_inp_sys_csi_str_mon_css_pixa_out,
  testbench_isp_inp_sys_csi_str_mon_css_pixb_out,
  testbench_isp_inp_sys_csi_str_mon_px_str_deint_0_out,
  testbench_isp_inp_sys_csi_str_mon_px_str_deint_1_out,
  testbench_isp_isel_i_prbs_st_data_a_out,
  testbench_isp_isel_i_prbs_st_data_b_out,
  testbench_isp_isel_tpg_st_data_a_out,
  testbench_isp_isel_tpg_st_data_b_out,
  testbench_isp_isel_fa_st_out,
  testbench_isp_isel_sf_fa_out,
  testbench_isp_isel_str2mipi_st_data_a_out,
  testbench_isp_isel_str2mipi_st_data_b_out,
  testbench_isp_isel_st_mux_st_data_out,
  testbench_isp_isel_st_mux_b_st_data_out,
  testbench_isp_ifmt_inp_sw_st_data_prim_out,
  testbench_isp_ifmt_inp_sw_st_data_prim_b_out,
  testbench_isp_ifmt_inp_sw_st_data_sec_out,
  testbench_isp_ifmt_inp_sw_st_data_mem_cpy_out,
  testbench_isp_ifmt_inp_sw_st_data_mem_cpy_b_out,
  testbench_isp_ifmt_ift_prim_st_sync_out,
  testbench_isp_ifmt_ift_prim_b_st_sync_out,
  testbench_isp_ifmt_ift_sec_st_sync_out,
  testbench_isp_ifmt_mem_cpy_st_sync_out,
  testbench_isp_ifa_sw_mux_st_out,
  testbench_isp_ifa_sw_demux_sta_out,
  testbench_isp_ifa_sw_demux_stb_out,
  testbench_isp_ifb_sw_mux_st_out,
  testbench_isp_ifb_sw_demux_sta_out,
  testbench_isp_ifb_sw_demux_stb_out,
  testbench_isp_gdc1_sw_mux_st_out,
  testbench_isp_gdc1_sw_demux_sta_out,
  testbench_isp_gdc1_sw_demux_stb_out,
  testbench_isp_gdc2_sw_mux_st_out,
  testbench_isp_gdc2_sw_demux_sta_out,
  testbench_isp_gdc2_sw_demux_stb_out,
  testbench_isp_gpd_irq_ctrl_irq_str_out,
  hrt_num_stream_out_ports
};

#endif /* _hive_isp_css_2400_system_hrtx_h_hrt_ */
