/*
 * Support for Medfield PNW Camera Imaging ISP subsystem.
 *
 * Copyright (c) 2010 Intel Corporation. All Rights Reserved.
 *
 * Copyright (c) 2010 Silicon Hive www.siliconhive.com.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version
 * 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 *
 */

#ifndef _host_h_hrt_
#define _host_h_hrt_

//#include <hrt/api.h>
#include <linux/delay.h>
#include <linux/slab.h>
#include "hive_isp_css_2400_system_hrtx.h"
#include "master_to_slave_hrt.h"
#include <scalar_processor_2400_cell.h>
#include <isp2400_mamoiada_cell.h>

#define hrt_syscall_server(x)

//extern void hrt_sleep(void);

#define testbench_isp_isp_type isp2400_mamoiada
#define testbench_isp_ispisp2400_mamoiada_sl_ipstatctrl_cell_port_bus_slave_port                 testbench_isp_isp_sl_ipstatctrl
#define testbench_isp_ispisp2400_mamoiada_sl_ipstatctrl_cell_port_connected_cell_port(m)         isp2400_mamoiada_sl_ipstatctrl_cell_port
#define testbench_isp_ispisp2400_mamoiada_sl_ipstatctrl_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2400_mamoiada_sl_ipstatctrl_, m), _address)
#define testbench_isp_ispisp2400_mamoiada_sl_ipstatctrl_cell_port_connected_cell_port_message(m) NULL
#define testbench_isp_ispisp2400_mamoiada_sl_ipdmem_cell_port_bus_slave_port                 testbench_isp_isp_sl_ipdmem
#define testbench_isp_ispisp2400_mamoiada_sl_ipdmem_cell_port_connected_cell_port(m)         isp2400_mamoiada_sl_ipdmem_cell_port
#define testbench_isp_ispisp2400_mamoiada_sl_ipdmem_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2400_mamoiada_sl_ipdmem_, m), _address)
#define testbench_isp_ispisp2400_mamoiada_sl_ipdmem_cell_port_connected_cell_port_message(m) NULL
#define testbench_isp_ispisp2400_mamoiada_sl_ippmem_cell_port_bus_slave_port                 testbench_isp_isp_sl_ippmem
#define testbench_isp_ispisp2400_mamoiada_sl_ippmem_cell_port_connected_cell_port(m)         isp2400_mamoiada_sl_ippmem_cell_port
#define testbench_isp_ispisp2400_mamoiada_sl_ippmem_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2400_mamoiada_sl_ippmem_, m), _address)
#define testbench_isp_ispisp2400_mamoiada_sl_ippmem_cell_port_connected_cell_port_message(m) NULL
#define testbench_isp_ispisp2400_mamoiada_sl_ipvamem_cell_port_bus_slave_port                 testbench_isp_isp_sl_ipvamem
#define testbench_isp_ispisp2400_mamoiada_sl_ipvamem_cell_port_connected_cell_port(m)         isp2400_mamoiada_sl_ipvamem_cell_port
#define testbench_isp_ispisp2400_mamoiada_sl_ipvamem_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2400_mamoiada_sl_ipvamem_, m), _address)
#define testbench_isp_ispisp2400_mamoiada_sl_ipvamem_cell_port_connected_cell_port_message(m) NULL
#define testbench_isp_ispisp2400_mamoiada_sl_iphist_cell_port_bus_slave_port                 testbench_isp_isp_sl_iphist
#define testbench_isp_ispisp2400_mamoiada_sl_iphist_cell_port_connected_cell_port(m)         isp2400_mamoiada_sl_iphist_cell_port
#define testbench_isp_ispisp2400_mamoiada_sl_iphist_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2400_mamoiada_sl_iphist_, m), _address)
#define testbench_isp_ispisp2400_mamoiada_sl_iphist_cell_port_connected_cell_port_message(m) NULL
#define testbench_isp_ispisp2400_mamoiada_simd_ipdma_cell_port_bus_slave_port                 testbench_isp_isp_simd_ipdma
#define testbench_isp_ispisp2400_mamoiada_simd_ipdma_cell_port_connected_cell_port(m)         isp2400_mamoiada_simd_ipdma_cell_port
#define testbench_isp_ispisp2400_mamoiada_simd_ipdma_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(isp2400_mamoiada_simd_ipdma_, m), _address)
#define testbench_isp_ispisp2400_mamoiada_simd_ipdma_cell_port_connected_cell_port_message(m) NULL
#define testbench_isp_ispisp2400_mamoiada_unreachable_cell_port_connected_cell_port(m)         _hrt_unreachable_mem_port
#define testbench_isp_ispisp2400_mamoiada_unreachable_cell_port_connected_cell_port_address(m) 0xFFFFFFFF
#define testbench_isp_ispisp2400_mamoiada_unreachable_cell_port_connected_cell_port_message(m) "memory " HRTSTR(m) " is not connected to the bus"
#define testbench_isp_isp_hrt_unreachable_cell_port_bus_slave_port               _hrt_unreachable_slave_port
#define testbench_isp_scp_type scalar_processor_2400
#define testbench_isp_scpscalar_processor_2400_sl_ip0_cell_port_bus_slave_port                 testbench_isp_scp_sl_ip0
#define testbench_isp_scpscalar_processor_2400_sl_ip0_cell_port_connected_cell_port(m)         scalar_processor_2400_sl_ip0_cell_port
#define testbench_isp_scpscalar_processor_2400_sl_ip0_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(scalar_processor_2400_sl_ip0_, m), _address)
#define testbench_isp_scpscalar_processor_2400_sl_ip0_cell_port_connected_cell_port_message(m) NULL
#define testbench_isp_scpscalar_processor_2400_sl_ip1_cell_port_bus_slave_port                 testbench_isp_scp_sl_ip1
#define testbench_isp_scpscalar_processor_2400_sl_ip1_cell_port_connected_cell_port(m)         scalar_processor_2400_sl_ip1_cell_port
#define testbench_isp_scpscalar_processor_2400_sl_ip1_cell_port_connected_cell_port_address(m) HRTCAT(HRTCAT(scalar_processor_2400_sl_ip1_, m), _address)
#define testbench_isp_scpscalar_processor_2400_sl_ip1_cell_port_connected_cell_port_message(m) NULL
#define testbench_isp_scpscalar_processor_2400_unreachable_cell_port_connected_cell_port(m)         _hrt_unreachable_mem_port
#define testbench_isp_scpscalar_processor_2400_unreachable_cell_port_connected_cell_port_address(m) 0xFFFFFFFF
#define testbench_isp_scpscalar_processor_2400_unreachable_cell_port_connected_cell_port_message(m) "memory " HRTSTR(m) " is not connected to the bus"
#define testbench_isp_scp_hrt_unreachable_cell_port_bus_slave_port               _hrt_unreachable_slave_port

/* Device properties: */
#define _hrt_device_host_property_NoDefaultResetGate 0x1
#define _hrt_device_host_property_MasterHost 0x1
#define _hrt_device_recorder_property_filename command_file_rec
#define _hrt_device_player_property_filename command_file
#define _hrt_device_testbench_master_rec_property_filename wide_mst_cmd_file
#define _hrt_device_testbench_master_rec_property_IsNotHostRecorder 0x1
#define _hrt_device_testbench_master_rec_property_UseCIOExtSRMD 0x1
#define _hrt_device_testbench_master_rec_property_UseCIOExtRAccept 0x1
#define _hrt_device_testbench_ddram_property_Width 0x100
#define _hrt_device_testbench_ddram_property_Capacity 0x3F8000
#define _hrt_device_testbench_ddram_property_rtl_capacity 0x3F8000
#define _hrt_device_testbench_ddram_property_UseCIOExtRAccept 0x1
#define _hrt_device_testbench_ddram_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_ddram_small_property_Width 0x100
#define _hrt_device_testbench_ddram_small_property_Capacity 0x80
#define _hrt_device_testbench_ddram_small_property_rtl_capacity 0x80
#define _hrt_device_testbench_ddram_small_property_UseCIOExtRAccept 0x1
#define _hrt_device_testbench_ddram_small_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_gdc1_property_elements_per_vector 0x40
#define _hrt_device_testbench_isp_gdc1_property_max_bits_per_element 0xE
#define _hrt_device_testbench_isp_gdc1_property_memory_capacity 0x800
#define _hrt_device_testbench_isp_gdc2_property_elements_per_vector 0x40
#define _hrt_device_testbench_isp_gdc2_property_max_bits_per_element 0xE
#define _hrt_device_testbench_isp_gdc2_property_memory_capacity 0x800
#define _hrt_device_testbench_isp_isp_property_NoDefaultResetGate 0x1
#define _hrt_device_testbench_isp_isp_property_UseCIOExtRAccept 0x1
#define _hrt_device_testbench_isp_isp_dma_property_UseCIOExt2DBlock 0x1
#define _hrt_device_testbench_isp_isp_dma_property_UseCIOExtRAccept 0x1
#define _hrt_device_testbench_isp_isp_dma_property_UseCIOExtSRMD 0x1
#define _hrt_device_testbench_isp_isp_dma_property_MaxNumChannels 0x20
#define _hrt_device_testbench_isp_isp_dma_property_CtrlAckFifoDepth 0x2
#define _hrt_device_testbench_isp_isp_dma_property_CommandFifoDepth 0x18
#define _hrt_device_testbench_isp_isp_dma_property_CommandFifoRdLat 0x0
#define _hrt_device_testbench_isp_isp_dma_property_CommandFifoRdLatBypass false
#define _hrt_device_testbench_isp_sf_isp2sp_property_BufferSize 0x10
#define _hrt_device_testbench_isp_sf_isp2sp_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_isp2sp_property_Width 0x20
#define _hrt_device_testbench_isp_sf_isp2sp_property_Capacity 0x10
#define _hrt_device_testbench_isp_sf_sp2isp_property_BufferSize 0x10
#define _hrt_device_testbench_isp_sf_sp2isp_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_sp2isp_property_Width 0x20
#define _hrt_device_testbench_isp_sf_sp2isp_property_Capacity 0x10
#define _hrt_device_testbench_isp_sf_cells2pifa_property_BufferSize 0x2
#define _hrt_device_testbench_isp_sf_cells2pifa_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_cells2pifa_property_Width 0x20
#define _hrt_device_testbench_isp_sf_cells2pifa_property_Capacity 0x2
#define _hrt_device_testbench_isp_sf_pifa2cells_property_BufferSize 0x2
#define _hrt_device_testbench_isp_sf_pifa2cells_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_pifa2cells_property_Width 0x20
#define _hrt_device_testbench_isp_sf_pifa2cells_property_Capacity 0x2
#define _hrt_device_testbench_isp_sf_cells2pifb_property_BufferSize 0x2
#define _hrt_device_testbench_isp_sf_cells2pifb_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_cells2pifb_property_Width 0x20
#define _hrt_device_testbench_isp_sf_cells2pifb_property_Capacity 0x2
#define _hrt_device_testbench_isp_sf_pifb2cells_property_BufferSize 0x2
#define _hrt_device_testbench_isp_sf_pifb2cells_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_pifb2cells_property_Width 0x20
#define _hrt_device_testbench_isp_sf_pifb2cells_property_Capacity 0x2
#define _hrt_device_testbench_isp_sf_sp2sif_property_BufferSize 0x2
#define _hrt_device_testbench_isp_sf_sp2sif_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_sp2sif_property_Width 0x20
#define _hrt_device_testbench_isp_sf_sp2sif_property_Capacity 0x2
#define _hrt_device_testbench_isp_sf_sif2sp_property_BufferSize 0x2
#define _hrt_device_testbench_isp_sf_sif2sp_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_sif2sp_property_Width 0x20
#define _hrt_device_testbench_isp_sf_sif2sp_property_Capacity 0x2
#define _hrt_device_testbench_isp_sf_sp2mc_property_BufferSize 0x7
#define _hrt_device_testbench_isp_sf_sp2mc_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_sp2mc_property_Width 0x20
#define _hrt_device_testbench_isp_sf_sp2mc_property_Capacity 0x7
#define _hrt_device_testbench_isp_sf_mc2sp_property_BufferSize 0x4
#define _hrt_device_testbench_isp_sf_mc2sp_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_mc2sp_property_Width 0x20
#define _hrt_device_testbench_isp_sf_mc2sp_property_Capacity 0x4
#define _hrt_device_testbench_isp_sf_sp2inpsys_property_BufferSize 0x4
#define _hrt_device_testbench_isp_sf_sp2inpsys_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_sp2inpsys_property_Width 0x20
#define _hrt_device_testbench_isp_sf_sp2inpsys_property_Capacity 0x4
#define _hrt_device_testbench_isp_sf_inpsys2sp_property_BufferSize 0x4
#define _hrt_device_testbench_isp_sf_inpsys2sp_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_inpsys2sp_property_Width 0x20
#define _hrt_device_testbench_isp_sf_inpsys2sp_property_Capacity 0x4
#define _hrt_device_testbench_isp_sf_isp2dma_property_BufferSize 0x2
#define _hrt_device_testbench_isp_sf_isp2dma_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_isp2dma_property_Width 0x20
#define _hrt_device_testbench_isp_sf_isp2dma_property_Capacity 0x2
#define _hrt_device_testbench_isp_sf_dma2isp_property_BufferSize 0x20
#define _hrt_device_testbench_isp_sf_dma2isp_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_dma2isp_property_Width 0x20
#define _hrt_device_testbench_isp_sf_dma2isp_property_Capacity 0x20
#define _hrt_device_testbench_isp_sf_sp2dma_property_BufferSize 0x2
#define _hrt_device_testbench_isp_sf_sp2dma_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_sp2dma_property_Width 0x20
#define _hrt_device_testbench_isp_sf_sp2dma_property_Capacity 0x2
#define _hrt_device_testbench_isp_sf_dma2sp_property_BufferSize 0x20
#define _hrt_device_testbench_isp_sf_dma2sp_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_dma2sp_property_Width 0x20
#define _hrt_device_testbench_isp_sf_dma2sp_property_Capacity 0x20
#define _hrt_device_testbench_isp_sf_cells2gdc_property_BufferSize 0x1E
#define _hrt_device_testbench_isp_sf_cells2gdc_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_cells2gdc_property_Width 0x20
#define _hrt_device_testbench_isp_sf_cells2gdc_property_Capacity 0x1E
#define _hrt_device_testbench_isp_sf_gdc2cells_property_BufferSize 0xC
#define _hrt_device_testbench_isp_sf_gdc2cells_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_gdc2cells_property_Width 0x20
#define _hrt_device_testbench_isp_sf_gdc2cells_property_Capacity 0xC
#define _hrt_device_testbench_isp_sf_cells2gdc2_property_BufferSize 0x8
#define _hrt_device_testbench_isp_sf_cells2gdc2_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_cells2gdc2_property_Width 0x20
#define _hrt_device_testbench_isp_sf_cells2gdc2_property_Capacity 0x8
#define _hrt_device_testbench_isp_sf_gdc22cells_property_BufferSize 0x4
#define _hrt_device_testbench_isp_sf_gdc22cells_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_gdc22cells_property_Width 0x20
#define _hrt_device_testbench_isp_sf_gdc22cells_property_Capacity 0x4
#define _hrt_device_testbench_isp_SPStrMon_property_Width 0x20
#define _hrt_device_testbench_isp_SPStrMon_B_property_Width 0x20
#define _hrt_device_testbench_isp_ISPStrMon_property_Width 0x20
#define _hrt_device_testbench_isp_ModStrMon_property_Width 0x20
#define _hrt_device_testbench_isp_scp_property_NoDefaultResetGate 0x1
#define _hrt_device_testbench_isp_scp_property_UseCIOExtRAccept 0x1
#define _hrt_device_testbench_isp_fa_sp_isp_property_Width 0x20
#define _hrt_device_testbench_isp_sf_sp2fa_property_BufferSize 0x2
#define _hrt_device_testbench_isp_sf_sp2fa_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_sp2fa_property_Width 0x20
#define _hrt_device_testbench_isp_sf_sp2fa_property_Capacity 0x2
#define _hrt_device_testbench_isp_sf_fa2sp_property_BufferSize 0x2
#define _hrt_device_testbench_isp_sf_fa2sp_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_fa2sp_property_Width 0x20
#define _hrt_device_testbench_isp_sf_fa2sp_property_Capacity 0x2
#define _hrt_device_testbench_isp_sf_isp2fa_property_BufferSize 0x2
#define _hrt_device_testbench_isp_sf_isp2fa_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_isp2fa_property_Width 0x20
#define _hrt_device_testbench_isp_sf_isp2fa_property_Capacity 0x2
#define _hrt_device_testbench_isp_sf_fa2isp_property_BufferSize 0x2
#define _hrt_device_testbench_isp_sf_fa2isp_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_sf_fa2isp_property_Width 0x20
#define _hrt_device_testbench_isp_sf_fa2isp_property_Capacity 0x2
#define _hrt_device_testbench_isp_jtag2cio_property_UseCIOExtSRMD 0x1
#define _hrt_device_testbench_isp_jtag2cio_property_UseCIOExtRAccept 0x1
#define _hrt_device_testbench_isp_jtag2cio_property_UseCIOExt2DBlock 0x1
#define _hrt_device_testbench_isp_jtag2cio_property_ir_code_BYPASS 0xF
#define _hrt_device_testbench_isp_jtag2cio_property_ir_code_SAMPLE 0x0
#define _hrt_device_testbench_isp_jtag2cio_property_ir_code_PRELOAD 0x1
#define _hrt_device_testbench_isp_jtag2cio_property_ir_code_EXTEST 0x2
#define _hrt_device_testbench_isp_jtag2cio_property_ir_code_IDCODE 0x3
#define _hrt_device_testbench_isp_jtag2cio_property_ir_code_PLD_CIOCMD 0x4
#define _hrt_device_testbench_isp_jtag2cio_property_ir_code_PLD_CIOADDR 0x5
#define _hrt_device_testbench_isp_jtag2cio_property_ir_code_PLD_CIOWDATA 0x6
#define _hrt_device_testbench_isp_jtag2cio_property_ir_code_SPL_CIORDATA 0x7
#define _hrt_device_testbench_isp_jtag2cio_property_use_tdo_tristate 0x0
#define _hrt_device_testbench_isp_jtag2cio_property_use_tdo_active 0x0
#define _hrt_device_testbench_isp_jtag2cio_property_UseDeviceId 0x1
#define _hrt_device_testbench_isp_jtag2cio_property_DeviceManufacturerId 0x298
#define _hrt_device_testbench_isp_jtag2cio_property_DevicePartNumber 0x4182
#define _hrt_device_testbench_isp_jtag2cio_property_DeviceVersion 0x0
#define _hrt_device_testbench_isp_inp_sys_sf_strmon2strmc_a_property_BufferSize 0x10
#define _hrt_device_testbench_isp_inp_sys_sf_strmon2strmc_a_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_sf_strmon2strmc_a_property_Width 0x21
#define _hrt_device_testbench_isp_inp_sys_sf_strmon2strmc_a_property_Capacity 0x10
#define _hrt_device_testbench_isp_inp_sys_sf_strmon2strmc_b_property_BufferSize 0x10
#define _hrt_device_testbench_isp_inp_sys_sf_strmon2strmc_b_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_sf_strmon2strmc_b_property_Width 0x21
#define _hrt_device_testbench_isp_inp_sys_sf_strmon2strmc_b_property_Capacity 0x10
#define _hrt_device_testbench_isp_inp_sys_sf_strmon2strmc_c_property_BufferSize 0x10
#define _hrt_device_testbench_isp_inp_sys_sf_strmon2strmc_c_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_sf_strmon2strmc_c_property_Width 0x21
#define _hrt_device_testbench_isp_inp_sys_sf_strmon2strmc_c_property_Capacity 0x10
#define _hrt_device_testbench_isp_inp_sys_stream_multicast_a_property_NoOutputEnabledStall 0x0
#define _hrt_device_testbench_isp_inp_sys_stream_multicast_b_property_NoOutputEnabledStall 0x0
#define _hrt_device_testbench_isp_inp_sys_stream_multicast_c_property_NoOutputEnabledStall 0x0
#define _hrt_device_testbench_isp_inp_sys_stream_mux_property_EnableNullInput 0x0
#define _hrt_device_testbench_isp_inp_sys_stream_mux_property_BlockingNullInput 0x0
#define _hrt_device_testbench_isp_inp_sys_stream_mux_property_OutputFifoDepth 0x30
#define _hrt_device_testbench_isp_inp_sys_inp_ctrl_property_DeviceCmdFifoDepth 0x4
#define _hrt_device_testbench_isp_inp_sys_inp_ctrl_property_DeviceAckFifoDepth 0x4
#define _hrt_device_testbench_isp_inp_sys_dma_property_UseCIOExt2DBlock 0x1
#define _hrt_device_testbench_isp_inp_sys_dma_property_UseCIOExtRAccept 0x1
#define _hrt_device_testbench_isp_inp_sys_dma_property_UseCIOExtSRMD 0x1
#define _hrt_device_testbench_isp_inp_sys_dma_property_MaxNumChannels 0x1
#define _hrt_device_testbench_isp_inp_sys_dma_property_CtrlAckFifoDepth 0x3
#define _hrt_device_testbench_isp_inp_sys_dma_property_CommandFifoDepth 0x2
#define _hrt_device_testbench_isp_inp_sys_dma_property_CommandFifoRdLat 0x0
#define _hrt_device_testbench_isp_inp_sys_dma_property_CommandFifoRdLatBypass false
#define _hrt_device_testbench_isp_inp_sys_dma_property_has_no_pack true
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2capta_property_BufferSize 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2capta_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2capta_property_Width 0x20
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2capta_property_Capacity 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_capta2ctrl_property_BufferSize 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_capta2ctrl_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_sf_capta2ctrl_property_Width 0x20
#define _hrt_device_testbench_isp_inp_sys_sf_capta2ctrl_property_Capacity 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2captb_property_BufferSize 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2captb_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2captb_property_Width 0x20
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2captb_property_Capacity 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_captb2ctrl_property_BufferSize 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_captb2ctrl_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_sf_captb2ctrl_property_Width 0x20
#define _hrt_device_testbench_isp_inp_sys_sf_captb2ctrl_property_Capacity 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2captc_property_BufferSize 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2captc_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2captc_property_Width 0x20
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2captc_property_Capacity 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_captc2ctrl_property_BufferSize 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_captc2ctrl_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_sf_captc2ctrl_property_Width 0x20
#define _hrt_device_testbench_isp_inp_sys_sf_captc2ctrl_property_Capacity 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2acq_property_BufferSize 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2acq_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2acq_property_Width 0x20
#define _hrt_device_testbench_isp_inp_sys_sf_ctrl2acq_property_Capacity 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_acq2ctrl_property_BufferSize 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_acq2ctrl_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_sf_acq2ctrl_property_Width 0x20
#define _hrt_device_testbench_isp_inp_sys_sf_acq2ctrl_property_Capacity 0x4
#define _hrt_device_testbench_isp_inp_sys_sf_csi2adptr_property_BufferSize 0x2
#define _hrt_device_testbench_isp_inp_sys_sf_csi2adptr_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_sf_csi2adptr_property_Width 0x20
#define _hrt_device_testbench_isp_inp_sys_sf_csi2adptr_property_Capacity 0x2
#define _hrt_device_testbench_isp_inp_sys_fifo_adapter_property_Width 0x20
#define _hrt_device_testbench_isp_inp_sys_csi_str_mon_property_Width 0x21
#define _hrt_device_testbench_isp_inp_sys_input_buffer_property_BSELWidth 0x8
#define _hrt_device_testbench_isp_inp_sys_input_buffer_property_UseCIOExtRAccept 0x1
#define _hrt_device_testbench_isp_inp_sys_input_buffer_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_inp_sys_input_buffer_property_Width 0x100
#define _hrt_device_testbench_isp_inp_sys_input_buffer_property_Capacity 0x180
#define _hrt_device_testbench_isp_isel_sync_gen_property_LongSyncs 0x0
#define _hrt_device_testbench_isp_isel_fa_property_Width 0x1A
#define _hrt_device_testbench_isp_isel_sf_fa_property_BufferSize 0x2
#define _hrt_device_testbench_isp_isel_sf_fa_property_Dbg_device_not_included 0x1
#define _hrt_device_testbench_isp_isel_sf_fa_property_Width 0x1A
#define _hrt_device_testbench_isp_isel_sf_fa_property_Capacity 0x2
#define _hrt_device_testbench_isp_isel_st_mux_property_EnableNullInput 0x0
#define _hrt_device_testbench_isp_isel_st_mux_property_BlockingNullInput 0x0
#define _hrt_device_testbench_isp_isel_st_mux_b_property_EnableNullInput 0x0
#define _hrt_device_testbench_isp_isel_st_mux_b_property_BlockingNullInput 0x0
#define _hrt_device_testbench_isp_ifmt_ift_prim_property_FifoDepth 0x4
#define _hrt_device_testbench_isp_ifmt_ift_prim_property_ElementsPerBlock 0x40
#define _hrt_device_testbench_isp_ifmt_ift_prim_property_BitsPerElement 0xE
#define _hrt_device_testbench_isp_ifmt_ift_prim_property_NumBlockBuffers 0x3
#define _hrt_device_testbench_isp_ifmt_ift_prim_property_UseLegacyImplementation 0x0
#define _hrt_device_testbench_isp_ifmt_ift_prim_property_CRunVectorWidth 0x380
#define _hrt_device_testbench_isp_ifmt_ift_prim_b_property_FifoDepth 0x4
#define _hrt_device_testbench_isp_ifmt_ift_prim_b_property_ElementsPerBlock 0x40
#define _hrt_device_testbench_isp_ifmt_ift_prim_b_property_BitsPerElement 0xE
#define _hrt_device_testbench_isp_ifmt_ift_prim_b_property_NumBlockBuffers 0x2
#define _hrt_device_testbench_isp_ifmt_ift_prim_b_property_UseLegacyImplementation 0x0
#define _hrt_device_testbench_isp_ifmt_ift_prim_b_property_CRunVectorWidth 0x380
#define _hrt_device_testbench_isp_ifmt_ift_sec_property_FifoDepth 0x4
#define _hrt_device_testbench_isp_ifmt_ift_sec_property_ElementsPerBlock 0x2
#define _hrt_device_testbench_isp_ifmt_ift_sec_property_BitsPerElement 0x10
#define _hrt_device_testbench_isp_ifmt_ift_sec_property_NumBlockBuffers 0x4
#define _hrt_device_testbench_isp_ifmt_ift_sec_property_UseLegacyImplementation 0x0
#define _hrt_device_testbench_isp_ifmt_ift_sec_property_CRunVectorWidth 0x20
#define _hrt_device_testbench_isp_ifmt_mem_cpy_property_FifoDepth 0x4
#define _hrt_device_testbench_isp_ifmt_mem_cpy_property_NumBuffers 0x2
#define _hrt_device_testbench_isp_ifa_sw_mux_property_EnableNullInput 0x0
#define _hrt_device_testbench_isp_ifa_sw_mux_property_BlockingNullInput 0x0
#define _hrt_device_testbench_isp_ifa_sw_demux_property_EnableNullOutput 0x0
#define _hrt_device_testbench_isp_ifa_sw_demux_property_BlockingNullOutput 0x0
#define _hrt_device_testbench_isp_ifb_sw_mux_property_EnableNullInput 0x0
#define _hrt_device_testbench_isp_ifb_sw_mux_property_BlockingNullInput 0x0
#define _hrt_device_testbench_isp_ifb_sw_demux_property_EnableNullOutput 0x0
#define _hrt_device_testbench_isp_ifb_sw_demux_property_BlockingNullOutput 0x0
#define _hrt_device_testbench_isp_gdc1_sw_mux_property_EnableNullInput 0x0
#define _hrt_device_testbench_isp_gdc1_sw_mux_property_BlockingNullInput 0x0
#define _hrt_device_testbench_isp_gdc1_sw_demux_property_EnableNullOutput 0x0
#define _hrt_device_testbench_isp_gdc1_sw_demux_property_BlockingNullOutput 0x0
#define _hrt_device_testbench_isp_gdc2_sw_mux_property_EnableNullInput 0x0
#define _hrt_device_testbench_isp_gdc2_sw_mux_property_BlockingNullInput 0x0
#define _hrt_device_testbench_isp_gdc2_sw_demux_property_EnableNullOutput 0x0
#define _hrt_device_testbench_isp_gdc2_sw_demux_property_BlockingNullOutput 0x0
#define _hrt_device_testbench_isp_gpd_c_gpio_property_clk_sync_buffers 0x2
#define _hrt_device_testbench_isp_gpd_tc_property_fifo_depth 0x100
#define _hrt_device_testbench_isp_gpd_gptimer_property_NumTimers 0x8
#define _hrt_device_testbench_isp_gpd_gptimer_property_NumIRQs 0x2
#define _hrt_device_testbench_isp_out_sys_addr_trans_property_PageBytes 0x1000
#define _hrt_device_testbench_isp_out_sys_addr_trans_property_page_numbers_iso_page_addresses 0x1
#define _hrt_device_testbench_isp_out_sys_addr_trans_property_UseCIOExtSRMD 0x1
#define _hrt_device_testbench_isp_out_sys_addr_trans_property_UseCIOExtRAccept 0x1
#define _hrt_device_testbench_isp_out_sys_addr_trans_property_UseCIOExt2DBlock 0x1
#define _hrt_device_testbench_isp_out_sys_c_mmu_property_TLBSets 0x10
#define _hrt_device_testbench_isp_out_sys_c_mmu_property_TLBSetBlocks 0x8
#define _hrt_device_testbench_isp_out_sys_c_mmu_property_TLBBlockElements 0x8
#define _hrt_device_testbench_isp_out_sys_c_mmu_property_PageTablesStorePageNumbersOnly 0x1
#define _hrt_device_testbench_isp_out_sys_c_mmu_property_PageTableLevels 0x2
#define _hrt_device_testbench_isp_out_sys_c_mmu_property_PageBytes 0x1000
#define _hrt_device_testbench_isp_out_sys_c_mmu_property_PhysAddrBits 0x24
#define _hrt_device_testbench_isp_out_sys_c_mmu_property_UseCIOExtRAccept 0x1


/* Cell initialization support: */
#define hrt_cell_init_testbench_isp_isp()\
{\
}

#define hrt_cell_init_testbench_isp_scp()\
{\
}

#define hrt_system_init()\
{\
  hrt_cell_init_testbench_isp_isp()\
  hrt_cell_init_testbench_isp_scp()\
}

/* System Memory support: */
#define testbench_ddram_size 0x7F00000
#define testbench_ddram_small_size 0x1000
#define testbench_isp_inp_sys_input_buffer_size 0x3000
/* Bus support: */
#define host_op0_data_width 0x20
#define recorder_sl_error_message "slave port recorder_sl is not connected to the bus"
#define recorder_sl_master_port_address 0xFFFFFFFF
#define recorder_mt_data_width 0x20
#define player_mt_data_width 0x20
#define i_host_bus_host_in_error_message NULL
#define i_host_bus_host_in_master_port_address 0x0
#define i_host_bus_bfm_play_in_error_message "slave port i_host_bus_bfm_play_in is not connected to the bus"
#define i_host_bus_bfm_play_in_master_port_address 0xFFFFFFFF
#define i_host_bus_out_data_width 0x20
#define testbench_sig_mon_slv_in_error_message NULL
#define testbench_sig_mon_slv_in_master_port_address 0x20000000
#define testbench_gp_adapter_slv_in_error_message NULL
#define testbench_gp_adapter_slv_in_master_port_address 0x60000000
#define testbench_master_rec_sl_error_message "slave port testbench_master_rec_sl is not connected to the bus"
#define testbench_master_rec_sl_master_port_address 0xFFFFFFFF
#define testbench_master_rec_mt_data_width 0x100
#define testbench_wide_bus_host_in_error_message NULL
#define testbench_wide_bus_host_in_master_port_address 0x80000000
#define testbench_wide_bus_isp_in_error_message "slave port testbench_wide_bus_isp_in is not connected to the bus"
#define testbench_wide_bus_isp_in_master_port_address 0xFFFFFFFF
#define testbench_wide_bus_mem_out_data_width 0x100
#define testbench_wide_bus_mem_sm_out_data_width 0x100
#define testbench_wide_bus_dum_out_data_width 0x100
#define testbench_ddram_ip0_error_message NULL
#define testbench_ddram_ip0_master_port_address 0x1A0000000ULL
#define testbench_ddram_small_ip0_error_message NULL
#define testbench_ddram_small_ip0_master_port_address 0xA80000000ULL
#define testbench_jtag_gpr_slv_in_error_message NULL
#define testbench_jtag_gpr_slv_in_master_port_address 0x40000000
#define testbench_isp_gdc1_sl_in_error_message NULL
#define testbench_isp_gdc1_sl_in_master_port_address 0x50000
#define testbench_isp_gdc1_mt_out_data_width 0x380
#define testbench_isp_gdc2_sl_in_error_message NULL
#define testbench_isp_gdc2_sl_in_master_port_address 0x60000
#define testbench_isp_gdc2_mt_out_data_width 0x380
#define testbench_isp_vec_bus_vec0_in_error_message "slave port testbench_isp_vec_bus_vec0_in is not connected to the bus"
#define testbench_isp_vec_bus_vec0_in_master_port_address 0xFFFFFFFF
#define testbench_isp_vec_bus_vec1_in_error_message "slave port testbench_isp_vec_bus_vec1_in is not connected to the bus"
#define testbench_isp_vec_bus_vec1_in_master_port_address 0xFFFFFFFF
#define testbench_isp_vec_bus_vec2_in_error_message "slave port testbench_isp_vec_bus_vec2_in is not connected to the bus"
#define testbench_isp_vec_bus_vec2_in_master_port_address 0xFFFFFFFF
#define testbench_isp_vec_bus_vec3_in_error_message "slave port testbench_isp_vec_bus_vec3_in is not connected to the bus"
#define testbench_isp_vec_bus_vec3_in_master_port_address 0xFFFFFFFF
#define testbench_isp_vec_bus_vec4_in_error_message "slave port testbench_isp_vec_bus_vec4_in is not connected to the bus"
#define testbench_isp_vec_bus_vec4_in_master_port_address 0xFFFFFFFF
#define testbench_isp_vec_bus_vec5_in_error_message NULL
#define testbench_isp_vec_bus_vec5_in_master_port_address 0x100000
#define testbench_isp_vec_bus_out_data_width 0x380
#define testbench_isp_isp_sl_ipstatctrl_error_message NULL
#define testbench_isp_isp_sl_ipstatctrl_master_port_address 0x20000
#define testbench_isp_isp_sl_ipdmem_error_message NULL
#define testbench_isp_isp_sl_ipdmem_master_port_address 0x200000
#define testbench_isp_isp_sl_ippmem_error_message NULL
#define testbench_isp_isp_sl_ippmem_master_port_address 0x180000
#define testbench_isp_isp_sl_ipvamem_error_message NULL
#define testbench_isp_isp_sl_ipvamem_master_port_address 0x1C0000
#define testbench_isp_isp_sl_iphist_error_message NULL
#define testbench_isp_isp_sl_iphist_master_port_address 0x1F0000
#define testbench_isp_isp_simd_ipdma_error_message NULL
#define testbench_isp_isp_simd_ipdma_master_port_address 0x100000
#define testbench_isp_isp_mt_opimaster_data_width 0x280
#define testbench_isp_isp_dma_ctrl_error_message NULL
#define testbench_isp_isp_dma_ctrl_master_port_address 0x40000
#define testbench_isp_isp_dma_master_port0_data_width 0x380
#define testbench_isp_isp_dma_master_port1_data_width 0x20
#define testbench_isp_isp_dma_master_port2_data_width 0x100
#define testbench_isp_scp_sl_ip0_error_message NULL
#define testbench_isp_scp_sl_ip0_master_port_address 0x10000
#define testbench_isp_scp_sl_ip1_error_message NULL
#define testbench_isp_scp_sl_ip1_master_port_address 0x300000
#define testbench_isp_scp_imt_op_data_width 0x40
#define testbench_isp_scp_mt_op_data_width 0x20
#define testbench_isp_data_bus_isp_dma_in_error_message "slave port testbench_isp_data_bus_isp_dma_in is not connected to the bus"
#define testbench_isp_data_bus_isp_dma_in_master_port_address 0xFFFFFFFF
#define testbench_isp_data_bus_scp_in_error_message "slave port testbench_isp_data_bus_scp_in is not connected to the bus"
#define testbench_isp_data_bus_scp_in_master_port_address 0xFFFFFFFF
#define testbench_isp_data_bus_isp_in_error_message "slave port testbench_isp_data_bus_isp_in is not connected to the bus"
#define testbench_isp_data_bus_isp_in_master_port_address 0xFFFFFFFF
#define testbench_isp_data_bus_inp_sys_dma_in_error_message "slave port testbench_isp_data_bus_inp_sys_dma_in is not connected to the bus"
#define testbench_isp_data_bus_inp_sys_dma_in_master_port_address 0xFFFFFFFF
#define testbench_isp_data_bus_out_data_width 0x100
#define testbench_isp_fa_sp_isp_sl_in_error_message NULL
#define testbench_isp_fa_sp_isp_sl_in_master_port_address 0x380000
#define testbench_isp_sf_sp2fa_out_rcv_address 0x380000
#define testbench_isp_sf_sp2fa_out_rcv_nb_address 0x380000
#define testbench_isp_sf_sp2fa_out_rcv_poll_address 0x380010
#define testbench_isp_sf_sp2fa_out_pre_fetch_address 0x380000
#define testbench_isp_sf_sp2fa_out_rcv_poll_bit 0
#define testbench_isp_fa_sp_isp_rcv_address 0x380000
#define testbench_isp_fa_sp_isp_rcv_nb_address 0x380000
#define testbench_isp_fa_sp_isp_rcv_poll_address 0x380010
#define testbench_isp_fa_sp_isp_pre_fetch_address 0x380000
#define testbench_isp_fa_sp_isp_rcv_poll_bit 0
#define testbench_isp_sf_fa2sp_in_snd_address 0x380008
#define testbench_isp_sf_fa2sp_in_snd_nb_address 0x380008
#define testbench_isp_sf_fa2sp_in_snd_poll_address 0x380018
#define testbench_isp_sf_fa2sp_in_snd_poll_bit 0
#define testbench_isp_fa_sp_isp_snd_address 0x380008
#define testbench_isp_fa_sp_isp_snd_nb_address 0x380008
#define testbench_isp_fa_sp_isp_snd_poll_address 0x380018
#define testbench_isp_fa_sp_isp_snd_poll_bit 0
#define testbench_isp_sf_isp2fa_out_rcv_address 0x380004
#define testbench_isp_sf_isp2fa_out_rcv_nb_address 0x380004
#define testbench_isp_sf_isp2fa_out_rcv_poll_address 0x380014
#define testbench_isp_sf_isp2fa_out_pre_fetch_address 0x380004
#define testbench_isp_sf_isp2fa_out_rcv_poll_bit 0
#define testbench_isp_sf_fa2isp_in_snd_address 0x38000C
#define testbench_isp_sf_fa2isp_in_snd_nb_address 0x38000C
#define testbench_isp_sf_fa2isp_in_snd_poll_address 0x38001C
#define testbench_isp_sf_fa2isp_in_snd_poll_bit 0
#define testbench_isp_host_bus_system_in_error_message NULL
#define testbench_isp_host_bus_system_in_master_port_address 0x0
#define testbench_isp_host_bus_narrow_bus_out_data_width 0x20
#define testbench_isp_host_bus_fa_out_data_width 0x20
#define testbench_isp_jtag2cio_ciom_data_width 0x8
#define testbench_isp_inp_sys_csi_receiver_ctrl_in_error_message NULL
#define testbench_isp_inp_sys_csi_receiver_ctrl_in_master_port_address 0x80000
#define testbench_isp_inp_sys_csi_receiver_ctrl_be_in_error_message NULL
#define testbench_isp_inp_sys_csi_receiver_ctrl_be_in_master_port_address 0x80800
#define testbench_isp_inp_sys_capt_unit_a_control_in_error_message NULL
#define testbench_isp_inp_sys_capt_unit_a_control_in_master_port_address 0x81000
#define testbench_isp_inp_sys_capt_unit_a_data_out_data_width 0x100
#define testbench_isp_inp_sys_capt_unit_b_control_in_error_message NULL
#define testbench_isp_inp_sys_capt_unit_b_control_in_master_port_address 0x82000
#define testbench_isp_inp_sys_capt_unit_b_data_out_data_width 0x100
#define testbench_isp_inp_sys_capt_unit_c_control_in_error_message NULL
#define testbench_isp_inp_sys_capt_unit_c_control_in_master_port_address 0x83000
#define testbench_isp_inp_sys_capt_unit_c_data_out_data_width 0x100
#define testbench_isp_inp_sys_acq_unit_control_in_error_message NULL
#define testbench_isp_inp_sys_acq_unit_control_in_master_port_address 0x84000
#define testbench_isp_inp_sys_acq_unit_data_in_data_width 0x100
#define testbench_isp_inp_sys_inp_ctrl_slv_error_message NULL
#define testbench_isp_inp_sys_inp_ctrl_slv_master_port_address 0x89000
#define testbench_isp_inp_sys_dma_ctrl_sl_error_message NULL
#define testbench_isp_inp_sys_dma_ctrl_sl_master_port_address 0x85000
#define testbench_isp_inp_sys_dma_ms0_data_width 0x100
#define testbench_isp_inp_sys_dma_ms1_data_width 0x100
#define testbench_isp_inp_sys_fifo_adapter_slv_in_error_message NULL
#define testbench_isp_inp_sys_fifo_adapter_slv_in_master_port_address 0x8B000
#define testbench_isp_inp_sys_csi_str_mon_fa_gensh_out_rcv_address 0x8B000
#define testbench_isp_inp_sys_csi_str_mon_fa_gensh_out_rcv_nb_address 0x8B000
#define testbench_isp_inp_sys_csi_str_mon_fa_gensh_out_rcv_poll_address 0x8B008
#define testbench_isp_inp_sys_csi_str_mon_fa_gensh_out_pre_fetch_address 0x8B000
#define testbench_isp_inp_sys_csi_str_mon_fa_gensh_out_rcv_poll_bit 0
#define testbench_isp_inp_sys_fifo_adapter_rcv_address 0x8B000
#define testbench_isp_inp_sys_fifo_adapter_rcv_nb_address 0x8B000
#define testbench_isp_inp_sys_fifo_adapter_rcv_poll_address 0x8B008
#define testbench_isp_inp_sys_fifo_adapter_pre_fetch_address 0x8B000
#define testbench_isp_inp_sys_fifo_adapter_rcv_poll_bit 0
#define testbench_isp_inp_sys_gpreg_slv_in_error_message NULL
#define testbench_isp_inp_sys_gpreg_slv_in_master_port_address 0x8A000
#define testbench_isp_inp_sys_irq_ctrl_slv_in_error_message NULL
#define testbench_isp_inp_sys_irq_ctrl_slv_in_master_port_address 0x8C000
#define testbench_isp_inp_sys_wide_bus_slv0_capt_a_error_message "slave port testbench_isp_inp_sys_wide_bus_slv0_capt_a is not connected to the bus"
#define testbench_isp_inp_sys_wide_bus_slv0_capt_a_master_port_address 0xFFFFFFFF
#define testbench_isp_inp_sys_wide_bus_slv1_capt_b_error_message "slave port testbench_isp_inp_sys_wide_bus_slv1_capt_b is not connected to the bus"
#define testbench_isp_inp_sys_wide_bus_slv1_capt_b_master_port_address 0xFFFFFFFF
#define testbench_isp_inp_sys_wide_bus_slv2_capt_c_error_message "slave port testbench_isp_inp_sys_wide_bus_slv2_capt_c is not connected to the bus"
#define testbench_isp_inp_sys_wide_bus_slv2_capt_c_master_port_address 0xFFFFFFFF
#define testbench_isp_inp_sys_wide_bus_slv3_acq_error_message "slave port testbench_isp_inp_sys_wide_bus_slv3_acq is not connected to the bus"
#define testbench_isp_inp_sys_wide_bus_slv3_acq_master_port_address 0xFFFFFFFF
#define testbench_isp_inp_sys_wide_bus_slv4_dma_error_message "slave port testbench_isp_inp_sys_wide_bus_slv4_dma is not connected to the bus"
#define testbench_isp_inp_sys_wide_bus_slv4_dma_master_port_address 0xFFFFFFFF
#define testbench_isp_inp_sys_wide_bus_slv5_ctrl_bus_error_message NULL
#define testbench_isp_inp_sys_wide_bus_slv5_ctrl_bus_master_port_address 0x8D000
#define testbench_isp_inp_sys_wide_bus_mt0_input_buf_data_width 0x100
#define testbench_isp_inp_sys_ctrl_bus_slv_ctrl_error_message NULL
#define testbench_isp_inp_sys_ctrl_bus_slv_ctrl_master_port_address 0x80000
#define testbench_isp_inp_sys_ctrl_bus_mt0_csi_data_width 0x20
#define testbench_isp_inp_sys_ctrl_bus_mt1_capt_a_data_width 0x20
#define testbench_isp_inp_sys_ctrl_bus_mt2_capt_b_data_width 0x20
#define testbench_isp_inp_sys_ctrl_bus_mt3_capt_c_data_width 0x20
#define testbench_isp_inp_sys_ctrl_bus_mt4_acq_data_width 0x20
#define testbench_isp_inp_sys_ctrl_bus_mt5_dma_data_width 0x20
#define testbench_isp_inp_sys_ctrl_bus_mt6_inp_ctrl_data_width 0x20
#define testbench_isp_inp_sys_ctrl_bus_mt7_gpreg_data_width 0x20
#define testbench_isp_inp_sys_ctrl_bus_mt8_fifo_adptr_data_width 0x20
#define testbench_isp_inp_sys_ctrl_bus_mt9_irq_ctrl_data_width 0x20
#define testbench_isp_inp_sys_ctrl_bus_mt10_wide_bus_data_width 0x20
#define testbench_isp_inp_sys_ctrl_bus_mt11_csi_be_data_width 0x20
#define testbench_isp_inp_sys_input_buffer_ip0_error_message NULL
#define testbench_isp_inp_sys_input_buffer_ip0_master_port_address 0x8D000
#define testbench_isp_isel_isel_bus_system_in_error_message NULL
#define testbench_isp_isel_isel_bus_system_in_master_port_address 0x90000
#define testbench_isp_isel_isel_bus_gpr_out_data_width 0x20
#define testbench_isp_isel_isel_bus_fa_out_data_width 0x20
#define testbench_isp_isel_isel_bus_irq_out_data_width 0x20
#define testbench_isp_isel_gpr_slv_in_error_message NULL
#define testbench_isp_isel_gpr_slv_in_master_port_address 0x90000
#define testbench_isp_isel_irq_ctrl_slv_in_error_message NULL
#define testbench_isp_isel_irq_ctrl_slv_in_master_port_address 0x90200
#define testbench_isp_isel_fa_sl_in_error_message NULL
#define testbench_isp_isel_fa_sl_in_master_port_address 0x90100
#define testbench_isp_isel_sf_fa_in_snd_address 0x90104
#define testbench_isp_isel_sf_fa_in_snd_nb_address 0x90104
#define testbench_isp_isel_sf_fa_in_snd_poll_address 0x9010C
#define testbench_isp_isel_sf_fa_in_snd_poll_bit 0
#define testbench_isp_isel_fa_snd_address 0x90104
#define testbench_isp_isel_fa_snd_nb_address 0x90104
#define testbench_isp_isel_fa_snd_poll_address 0x9010C
#define testbench_isp_isel_fa_snd_poll_bit 0
#define testbench_isp_ifmt_ift_prim_sl_in_error_message NULL
#define testbench_isp_ifmt_ift_prim_sl_in_master_port_address 0x30000
#define testbench_isp_ifmt_ift_prim_mt_out_data_width 0x380
#define testbench_isp_ifmt_ift_prim_b_sl_in_error_message NULL
#define testbench_isp_ifmt_ift_prim_b_sl_in_master_port_address 0x30200
#define testbench_isp_ifmt_ift_prim_b_mt_out_data_width 0x380
#define testbench_isp_ifmt_ift_sec_sl_in_error_message NULL
#define testbench_isp_ifmt_ift_sec_sl_in_master_port_address 0x30400
#define testbench_isp_ifmt_ift_sec_mt_out_data_width 0x20
#define testbench_isp_ifmt_mem_cpy_sl_in_error_message NULL
#define testbench_isp_ifmt_mem_cpy_sl_in_master_port_address 0x30600
#define testbench_isp_ifmt_mem_cpy_mt_out_data_width 0x20
#define testbench_isp_ifmt_gp_reg_slv_in_error_message NULL
#define testbench_isp_ifmt_gp_reg_slv_in_master_port_address 0x30800
#define testbench_isp_ifmt_irq_ctrl_slv_in_error_message NULL
#define testbench_isp_ifmt_irq_ctrl_slv_in_master_port_address 0x30A00
#define testbench_isp_ifmt_ctrl_bus_ctrl_in_error_message NULL
#define testbench_isp_ifmt_ctrl_bus_ctrl_in_master_port_address 0x30000
#define testbench_isp_ifmt_ctrl_bus_if_prim_sl_data_width 0x20
#define testbench_isp_ifmt_ctrl_bus_if_prim_b_sl_data_width 0x20
#define testbench_isp_ifmt_ctrl_bus_if_sec_sl_data_width 0x20
#define testbench_isp_ifmt_ctrl_bus_mcpy_sl_data_width 0x20
#define testbench_isp_ifmt_ctrl_bus_gp_regs_sl_data_width 0x20
#define testbench_isp_ifmt_ctrl_bus_irq_ctrl_sl_data_width 0x20
#define testbench_isp_gpd_gp_bus_system_in_error_message NULL
#define testbench_isp_gpd_gp_bus_system_in_master_port_address 0x0
#define testbench_isp_gpd_gp_bus_gpio_out_data_width 0x20
#define testbench_isp_gpd_gp_bus_gp_regs_out_data_width 0x20
#define testbench_isp_gpd_gp_bus_tc_out_data_width 0x20
#define testbench_isp_gpd_gp_bus_irq_out_data_width 0x20
#define testbench_isp_gpd_gp_bus_gptimer_out_data_width 0x20
#define testbench_isp_gpd_c_gpio_ctrl_in_error_message NULL
#define testbench_isp_gpd_c_gpio_ctrl_in_master_port_address 0x400
#define testbench_isp_gpd_tc_slv_in_error_message NULL
#define testbench_isp_gpd_tc_slv_in_master_port_address 0x100
#define testbench_isp_gpd_tc_mst_out_data_width 0x20
#define testbench_isp_gpd_gptimer_slv_in_error_message NULL
#define testbench_isp_gpd_gptimer_slv_in_master_port_address 0x600
#define testbench_isp_gpd_irq_ctrl_slv_in_error_message NULL
#define testbench_isp_gpd_irq_ctrl_slv_in_master_port_address 0x500
#define testbench_isp_gpd_gp_reg_slv_in_error_message NULL
#define testbench_isp_gpd_gp_reg_slv_in_master_port_address 0x0
#define testbench_isp_nar_bus_pnbus_ift_sec_in_error_message "slave port testbench_isp_nar_bus_pnbus_ift_sec_in is not connected to the bus"
#define testbench_isp_nar_bus_pnbus_ift_sec_in_master_port_address 0xFFFFFFFF
#define testbench_isp_nar_bus_pnbus_mem_cpy_in_error_message "slave port testbench_isp_nar_bus_pnbus_mem_cpy_in is not connected to the bus"
#define testbench_isp_nar_bus_pnbus_mem_cpy_in_master_port_address 0xFFFFFFFF
#define testbench_isp_nar_bus_pnbus_gpd_in_error_message "slave port testbench_isp_nar_bus_pnbus_gpd_in is not connected to the bus"
#define testbench_isp_nar_bus_pnbus_gpd_in_master_port_address 0xFFFFFFFF
#define testbench_isp_nar_bus_pnbus_narr_bus_out_data_width 0x20
#define testbench_isp_nar_bus_nbus_system_in_error_message NULL
#define testbench_isp_nar_bus_nbus_system_in_master_port_address 0x0
#define testbench_isp_nar_bus_nbus_scp_in_error_message "slave port testbench_isp_nar_bus_nbus_scp_in is not connected to the bus"
#define testbench_isp_nar_bus_nbus_scp_in_master_port_address 0xFFFFFFFF
#define testbench_isp_nar_bus_nbus_pre_nrr_in_error_message "slave port testbench_isp_nar_bus_nbus_pre_nrr_in is not connected to the bus"
#define testbench_isp_nar_bus_nbus_pre_nrr_in_master_port_address 0xFFFFFFFF
#define testbench_isp_nar_bus_nbus_dma_in_error_message "slave port testbench_isp_nar_bus_nbus_dma_in is not connected to the bus"
#define testbench_isp_nar_bus_nbus_dma_in_master_port_address 0xFFFFFFFF
#define testbench_isp_nar_bus_nbus_slv_grp_out_data_width 0x20
#define testbench_isp_nar_bus_nbus_scp_dmem_out_data_width 0x20
#define testbench_isp_nar_bus_nbus_isp_dmem_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_cfg_bus_in_error_message NULL
#define testbench_isp_slv_grp_bus_sgp_bus_cfg_bus_in_master_port_address 0x0
#define testbench_isp_slv_grp_bus_sgp_bus_gpd_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_scp_sc_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_isp_sc_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_ifmt_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_isp_dma_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_gdc_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_scaler_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_mmu_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_inp_sys_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_isel_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_vec_bus_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_isp_pmem_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_isp_vamem_out_data_width 0x20
#define testbench_isp_slv_grp_bus_sgp_bus_isp_hist_out_data_width 0x20
#define testbench_isp_out_sys_addr_trans_in_error_message "slave port testbench_isp_out_sys_addr_trans_in is not connected to the bus"
#define testbench_isp_out_sys_addr_trans_in_master_port_address 0xFFFFFFFF
#define testbench_isp_out_sys_addr_trans_data_out_data_width 0x100
#define testbench_isp_out_sys_addr_trans_mmu_out_data_width 0x20
#define testbench_isp_out_sys_c_mmu_ctrl_in_error_message NULL
#define testbench_isp_out_sys_c_mmu_ctrl_in_master_port_address 0x70000
#define testbench_isp_out_sys_c_mmu_request_in_error_message "slave port testbench_isp_out_sys_c_mmu_request_in is not connected to the bus"
#define testbench_isp_out_sys_c_mmu_request_in_master_port_address 0xFFFFFFFF
#define testbench_isp_out_sys_c_mmu_out_data_width 0x20
#define testbench_isp_out_sys_sec_data_bus_address_trans_in_error_message "slave port testbench_isp_out_sys_sec_data_bus_address_trans_in is not connected to the bus"
#define testbench_isp_out_sys_sec_data_bus_address_trans_in_master_port_address 0xFFFFFFFF
#define testbench_isp_out_sys_sec_data_bus_mmu_in_error_message "slave port testbench_isp_out_sys_sec_data_bus_mmu_in is not connected to the bus"
#define testbench_isp_out_sys_sec_data_bus_mmu_in_master_port_address 0xFFFFFFFF
#define testbench_isp_out_sys_sec_data_bus_out_data_width 0x100
#define testbench_system_bus_cio_bus_host_in_error_message NULL
#define testbench_system_bus_cio_bus_host_in_master_port_address 0x0
#define testbench_system_bus_cio_bus_isp_css_out_data_width 0x20
#define testbench_system_bus_cio_bus_gpio_out_data_width 0x20
#define testbench_system_bus_cio_bus_irq_mon_out_data_width 0x20
#define testbench_system_bus_cio_bus_wide_bus_out_data_width 0x20
#define testbench_system_bus_cio_bus_m_gpr_data_width 0x20
#define testbench_tb_ocp2cio_sl_error_message "slave port testbench_tb_ocp2cio_sl is not connected to the bus"
#define testbench_tb_ocp2cio_sl_master_port_address 0xFFFFFFFF
#define testbench_tb_ocp2cio_mt_data_width 0x100
#define testbench_sm2wide_sl_error_message NULL
#define testbench_sm2wide_sl_master_port_address 0x80000000
#define testbench_sm2wide_mt_data_width 0x100
#define testbench_wide_ce_sl_error_message NULL
#define testbench_wide_ce_sl_master_port_address 0x1A0000000ULL
#define testbench_wide_ce_mt_data_width 0x100
#define testbench_ddram_staller_sl_error_message NULL
#define testbench_ddram_staller_sl_master_port_address 0x1A0000000ULL
#define testbench_ddram_staller_mt_data_width 0x100
#define testbench_wide_ce_2_sl_error_message NULL
#define testbench_wide_ce_2_sl_master_port_address 0xA80000000ULL
#define testbench_wide_ce_2_mt_data_width 0x100
#define testbench_isp_ift_sec_pipe_sl_error_message "slave port testbench_isp_ift_sec_pipe_sl is not connected to the bus"
#define testbench_isp_ift_sec_pipe_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_ift_sec_pipe_mt_data_width 0x20
#define testbench_isp_cio_subword_conv_sl_error_message NULL
#define testbench_isp_cio_subword_conv_sl_master_port_address 0x100000
#define testbench_isp_cio_subword_conv_mt_data_width 0x380
#define testbench_isp_vec_bus_pipe_sl_error_message NULL
#define testbench_isp_vec_bus_pipe_sl_master_port_address 0x100000
#define testbench_isp_vec_bus_pipe_mt_data_width 0x380
#define testbench_isp_cio_conv_vamem_sl_error_message NULL
#define testbench_isp_cio_conv_vamem_sl_master_port_address 0x1C0000
#define testbench_isp_cio_conv_vamem_mt_data_width 0x10
#define testbench_isp_cio_conv_isp_sl_error_message "slave port testbench_isp_cio_conv_isp_sl is not connected to the bus"
#define testbench_isp_cio_conv_isp_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_cio_conv_isp_mt_data_width 0x100
#define testbench_isp_scp_pipe_sl_error_message "slave port testbench_isp_scp_pipe_sl is not connected to the bus"
#define testbench_isp_scp_pipe_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_scp_pipe_mt_data_width 0x40
#define testbench_isp_cio_conv_sp_sl_error_message "slave port testbench_isp_cio_conv_sp_sl is not connected to the bus"
#define testbench_isp_cio_conv_sp_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_cio_conv_sp_mt_data_width 0x100
#define testbench_isp_ocp2cio_nar_bus_sl_error_message NULL
#define testbench_isp_ocp2cio_nar_bus_sl_master_port_address 0x0
#define testbench_isp_ocp2cio_nar_bus_mt_data_width 0x20
#define testbench_isp_data_bus_pipe_sl_error_message "slave port testbench_isp_data_bus_pipe_sl is not connected to the bus"
#define testbench_isp_data_bus_pipe_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_data_bus_pipe_mt_data_width 0x100
#define testbench_isp_inp_sys_cio2ahb_sl_error_message NULL
#define testbench_isp_inp_sys_cio2ahb_sl_master_port_address 0x80000
#define testbench_isp_inp_sys_cio2ahb_mt_data_width 0x20
#define testbench_isp_inp_sys_cio_conv_sl_error_message NULL
#define testbench_isp_inp_sys_cio_conv_sl_master_port_address 0x8D000
#define testbench_isp_inp_sys_cio_conv_mt_data_width 0x100
#define testbench_isp_ifmt_pifa_pipe_sl_error_message "slave port testbench_isp_ifmt_pifa_pipe_sl is not connected to the bus"
#define testbench_isp_ifmt_pifa_pipe_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_ifmt_pifa_pipe_mt_data_width 0x380
#define testbench_isp_ifmt_pifb_pipe_sl_error_message "slave port testbench_isp_ifmt_pifb_pipe_sl is not connected to the bus"
#define testbench_isp_ifmt_pifb_pipe_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_ifmt_pifb_pipe_mt_data_width 0x380
#define testbench_isp_nar_bus_ift_sec_pipe_sl_error_message "slave port testbench_isp_nar_bus_ift_sec_pipe_sl is not connected to the bus"
#define testbench_isp_nar_bus_ift_sec_pipe_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_nar_bus_ift_sec_pipe_mt_data_width 0x20
#define testbench_isp_nar_bus_mem_cpy_pipe_sl_error_message "slave port testbench_isp_nar_bus_mem_cpy_pipe_sl is not connected to the bus"
#define testbench_isp_nar_bus_mem_cpy_pipe_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_nar_bus_mem_cpy_pipe_mt_data_width 0x20
#define testbench_isp_nar_bus_gpd_pipe_sl_error_message "slave port testbench_isp_nar_bus_gpd_pipe_sl is not connected to the bus"
#define testbench_isp_nar_bus_gpd_pipe_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_nar_bus_gpd_pipe_mt_data_width 0x20
#define testbench_isp_nar_bus_dma_pipe_sl_error_message "slave port testbench_isp_nar_bus_dma_pipe_sl is not connected to the bus"
#define testbench_isp_nar_bus_dma_pipe_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_nar_bus_dma_pipe_mt_data_width 0x20
#define testbench_isp_nar_bus_pn_bus_pipe_sl_error_message "slave port testbench_isp_nar_bus_pn_bus_pipe_sl is not connected to the bus"
#define testbench_isp_nar_bus_pn_bus_pipe_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_nar_bus_pn_bus_pipe_mt_data_width 0x20
#define testbench_isp_nar_bus_isp_dmem_slv_pipe_sl_error_message NULL
#define testbench_isp_nar_bus_isp_dmem_slv_pipe_sl_master_port_address 0x200000
#define testbench_isp_nar_bus_isp_dmem_slv_pipe_mt_data_width 0x20
#define testbench_isp_nar_bus_slv_grp_slv_pipe_sl_error_message NULL
#define testbench_isp_nar_bus_slv_grp_slv_pipe_sl_master_port_address 0x0
#define testbench_isp_nar_bus_slv_grp_slv_pipe_mt_data_width 0x20
#define testbench_isp_nar_bus_scp_slv_pipe_sl_error_message NULL
#define testbench_isp_nar_bus_scp_slv_pipe_sl_master_port_address 0x300000
#define testbench_isp_nar_bus_scp_slv_pipe_mt_data_width 0x20
#define testbench_isp_slv_grp_bus_mmu_slv_pipe_sl_error_message NULL
#define testbench_isp_slv_grp_bus_mmu_slv_pipe_sl_master_port_address 0x70000
#define testbench_isp_slv_grp_bus_mmu_slv_pipe_mt_data_width 0x20
#define testbench_isp_slv_grp_bus_dma_slv_pipe_sl_error_message NULL
#define testbench_isp_slv_grp_bus_dma_slv_pipe_sl_master_port_address 0x40000
#define testbench_isp_slv_grp_bus_dma_slv_pipe_mt_data_width 0x20
#define testbench_isp_slv_grp_bus_isys_slv_pipe_sl_error_message NULL
#define testbench_isp_slv_grp_bus_isys_slv_pipe_sl_master_port_address 0x80000
#define testbench_isp_slv_grp_bus_isys_slv_pipe_mt_data_width 0x20
#define testbench_isp_slv_grp_bus_vamem_slv_pipe_sl_error_message NULL
#define testbench_isp_slv_grp_bus_vamem_slv_pipe_sl_master_port_address 0x1C0000
#define testbench_isp_slv_grp_bus_vamem_slv_pipe_mt_data_width 0x20
#define testbench_isp_out_sys_at_req_pipe_sl_error_message "slave port testbench_isp_out_sys_at_req_pipe_sl is not connected to the bus"
#define testbench_isp_out_sys_at_req_pipe_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_out_sys_at_req_pipe_mt_data_width 0x20
#define testbench_isp_out_sys_cio_conv_mmu_sl_error_message "slave port testbench_isp_out_sys_cio_conv_mmu_sl is not connected to the bus"
#define testbench_isp_out_sys_cio_conv_mmu_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_out_sys_cio_conv_mmu_mt_data_width 0x100
#define testbench_isp_out_sys_cio2ocp_wide_data_out_sl_error_message "slave port testbench_isp_out_sys_cio2ocp_wide_data_out_sl is not connected to the bus"
#define testbench_isp_out_sys_cio2ocp_wide_data_out_sl_master_port_address 0xFFFFFFFF
#define testbench_isp_out_sys_cio2ocp_wide_data_out_mt_data_width 0x100
#define testbench_system_bus_tb_cio2ocp_sl_error_message NULL
#define testbench_system_bus_tb_cio2ocp_sl_master_port_address 0x0
#define testbench_system_bus_tb_cio2ocp_mt_data_width 0x20
#define HRT_INLINE static inline
/*
hive_bool hrt_cell_wait_timeout_testbench_isp_isp(hive_uint max_loops)
{
  hive_uint i;
  hrt_sleep();
  for (i=0; i<max_loops; i++) {
    hrt_sleep();
    if (hrt_ctl_is_ready(testbench_isp_isp)) return hive_false;
#ifndef HRT_HW
    else if (hrt_ctl_is_sleeping(testbench_isp_isp)) {
      hrt_syscall_server (testbench_isp_isp);
      hrt_ctl_start(testbench_isp_isp);
    }
#endif
    else hrt_sleep();
  }
  return hive_true;
}
HRT_INLINE hive_bool hrt_cell_wait_timeout_testbench_isp_scp(hive_uint max_loops)
{
  hive_uint i;
  hrt_sleep();
  for (i=0; i<max_loops; i++) {
    hrt_sleep();
    if (hrt_ctl_is_ready(testbench_isp_scp)) return hive_false;
#ifndef HRT_HW
    else if (hrt_ctl_is_sleeping(testbench_isp_scp)) {
      hrt_syscall_server (testbench_isp_scp);
      hrt_ctl_start(testbench_isp_scp);
    }
#endif
    else hrt_sleep();
  }
  return hive_true;
}
*/
//#include "hive_isp_css_2400_system_hrt_dbg.h"
#ifdef HRT_CSIM
/* Symbol that indicates for which host instance this hrt implementation is intended */
hive_host_id _hrt_host_0_present;
#endif


#endif /* _host_h_hrt_ */
