CFLAGS_pmu.o        := -Werror

obj-$(CONFIG_INTEL_MID_MDFLD_POWER)		+= pmu.o
obj-$(CONFIG_X86_MDFLD)		+= mfld.o
obj-$(CONFIG_BOARD_MFLD_BLACKBAY)		+= board-blackbay.o
obj-$(CONFIG_BOARD_REDRIDGE)	+= board-redridge.o
