CFLAGS_intel_idle.o				+= -Werror

obj-$(CONFIG_I7300_IDLE)			+= i7300_idle.o
obj-$(CONFIG_INTEL_IDLE)			+= intel_idle.o
obj-$(CONFIG_X86_MRST)				+= mrst_s0i3.o
obj-$(CONFIG_X86_MRST)				+= mrst_s0i3_asm.o
