ccflags-y += -DATOMISP_POSTFIX=\"css2400\" -DCONFIG_ISP2400 -DCONFIG_VIDEO_ATOMISP_CSS15
CONFIG_VIDEO_ATOMISP_CSS15 := m
CONFIG_ISP2400 := y
postfix := css2400

include $(srctree)/$(src)/../Makefile.common
