/*
* Support for Medfield PNW Camera Imaging ISP subsystem.
*
* Copyright (c) 2010 Intel Corporation. All Rights Reserved.
*
* Copyright (c) 2010 Silicon Hive www.siliconhive.com.
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License version
* 2 as published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301, USA.
*
*/

#ifndef _SH_CSS_BINARY_INFO_H_
#define _SH_CSS_BINARY_INFO_H_

#ifdef CONFIG_X86_MRFLD
#define SYSTEM_hive_isp_css_2400_system
#endif

#include "sh_css_defs.h"

/* Bayer DS */
#define ISP_BAYER_DS_BINARY_ID               SH_CSS_BINARY_ID_BAYER_DS
#define ISP_BAYER_DS_BINARY                  isp_bayer_ds_var
#define ISP_BAYER_DS_MODE                    SH_CSS_BINARY_MODE_BAYER_DS
#define ISP_BAYER_DS_OUTPUT_FRAME_FORMAT     SH_CSS_FRAME_FORMAT_RAW
#define ISP_BAYER_DS_ENABLE_DS               1
#define ISP_BAYER_DS_ENABLE_FPNR             0
#define ISP_BAYER_DS_ENABLE_SC               0
#define ISP_BAYER_DS_ENABLE_S3A              0
#define ISP_BAYER_DS_ENABLE_SDIS             0
#define ISP_BAYER_DS_ENABLE_VF_VECEVEN       0
#define ISP_BAYER_DS_ENABLE_UDS              0
#define ISP_BAYER_DS_PIPELINING              1
#define ISP_BAYER_DS_OUTPUT_NUM_CHUNKS       1
#define ISP_BAYER_DS_DUMMY_BUF_VECTORS       0
#define ISP_BAYER_DS_LEFT_CROPPING           0
#define ISP_BAYER_DS_TOP_CROPPING            0
#define ISP_BAYER_DS_ENABLE_DVS_ENVELOPE     0
#define ISP_BAYER_DS_MAX_DVS_ENVELOPE_WIDTH  0
#define ISP_BAYER_DS_MAX_DVS_ENVELOPE_HEIGHT 0
#define ISP_BAYER_DS_MAX_OUTPUT_WIDTH        SH_CSS_MAX_SENSOR_WIDTH
#define ISP_BAYER_DS_MAX_OUTPUT_HEIGHT       SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_BAYER_DS_MIN_OUTPUT_WIDTH        SH_CSS_MIN_SENSOR_WIDTH
#define ISP_BAYER_DS_MIN_OUTPUT_HEIGHT       SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_BAYER_DS_OUTPUT_FORMATS          { SH_CSS_FRAME_FORMAT_RAW }
#define ISP_BAYER_DS_MAX_VF_LOG_DOWNSCALE    0
#define ISP_BAYER_DS_INPUT                   SH_CSS_BINARY_INPUT_SENSOR
#define ISP_BAYER_DS_C_SUBSAMPLING           SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_BAYER_DS_FIXED_S3A_DECI_LOG      0

/* Capture PP */
#define ISP_CAPTURE_PP_BINARY_ID               SH_CSS_BINARY_ID_CAPTURE_PP
#define ISP_CAPTURE_PP_BINARY                  isp_capture_pp_var
#define ISP_CAPTURE_PP_MODE                    SH_CSS_BINARY_MODE_CAPTURE_PP
#define ISP_CAPTURE_PP_ENABLE_UDS              1
#define ISP_CAPTURE_PP_ENABLE_DS               1
#define ISP_CAPTURE_PP_ENABLE_VF_VECEVEN       1
#define ISP_CAPTURE_PP_ENABLE_FPNR             0
#define ISP_CAPTURE_PP_ENABLE_SC               0
#define ISP_CAPTURE_PP_ENABLE_S3A              0
#define ISP_CAPTURE_PP_ENABLE_SDIS             0
#define ISP_CAPTURE_PP_PIPELINING              1
#define ISP_CAPTURE_PP_OUTPUT_NUM_CHUNKS       2
#define ISP_CAPTURE_PP_DUMMY_BUF_VECTORS       0
#define ISP_CAPTURE_PP_LEFT_CROPPING           0
#define ISP_CAPTURE_PP_TOP_CROPPING            0
#define ISP_CAPTURE_PP_ENABLE_DVS_ENVELOPE     0
#define ISP_CAPTURE_PP_MAX_DVS_ENVELOPE_WIDTH  0
#define ISP_CAPTURE_PP_MAX_DVS_ENVELOPE_HEIGHT 0
/* max width currently limited because of VMEM shortage */
#define ISP_CAPTURE_PP_MAX_OUTPUT_WIDTH       MAX(4480, SH_CSS_MAX_SENSOR_WIDTH)
#define ISP_CAPTURE_PP_MAX_OUTPUT_HEIGHT       SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_CAPTURE_PP_MIN_OUTPUT_WIDTH        SH_CSS_MIN_SENSOR_WIDTH
#define ISP_CAPTURE_PP_MIN_OUTPUT_HEIGHT       SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_CAPTURE_PP_OUTPUT_FORMATS          SH_CSS_CAPTURE_OUTPUT_FORMATS
#define ISP_CAPTURE_PP_MAX_VF_LOG_DOWNSCALE    1
#define ISP_CAPTURE_PP_INPUT                   SH_CSS_BINARY_INPUT_MEMORY
#define ISP_CAPTURE_PP_C_SUBSAMPLING           SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_CAPTURE_PP_FIXED_S3A_DECI_LOG      0

/* Copy */
#define ISP_COPY_BINARY_ID                 SH_CSS_BINARY_ID_COPY
#define ISP_COPY_MODE                      SH_CSS_BINARY_MODE_COPY
#define ISP_COPY_BINARY                    isp_copy_var
#define ISP_COPY_ENABLE_DS                 0
#define ISP_COPY_ENABLE_FPNR               0
#define ISP_COPY_ENABLE_SC                 0
#define ISP_COPY_ENABLE_S3A                0
#define ISP_COPY_ENABLE_SDIS               0
#define ISP_COPY_ENABLE_VF_VECEVEN         0
#define ISP_COPY_ENABLE_UDS                0
#define ISP_COPY_PIPELINING                1
#define ISP_COPY_OUTPUT_NUM_CHUNKS         1
#define ISP_COPY_DUMMY_BUF_VECTORS         0
#define ISP_COPY_LEFT_CROPPING             0
#define ISP_COPY_TOP_CROPPING              0
#define ISP_COPY_ENABLE_DVS_ENVELOPE       0
#define ISP_COPY_MAX_DVS_ENVELOPE_WIDTH    0
#define ISP_COPY_MAX_DVS_ENVELOPE_HEIGHT   0
#define ISP_COPY_MAX_VF_LOG_DOWNSCALE      2
#define ISP_COPY_MAX_OUTPUT_WIDTH          SH_CSS_MAX_SENSOR_WIDTH
#define ISP_COPY_MAX_OUTPUT_HEIGHT         SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_COPY_MIN_OUTPUT_WIDTH          SH_CSS_MIN_SENSOR_WIDTH
#define ISP_COPY_MIN_OUTPUT_HEIGHT         SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_COPY_INPUT                     SH_CSS_BINARY_INPUT_SENSOR
#define ISP_COPY_C_SUBSAMPLING             SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_COPY_FIXED_S3A_DECI_LOG        0
#define ISP_COPY_OUTPUT_FORMATS \
	{ \
		SH_CSS_FRAME_FORMAT_NV11, \
		SH_CSS_FRAME_FORMAT_NV12, \
		SH_CSS_FRAME_FORMAT_NV16, \
		SH_CSS_FRAME_FORMAT_NV21, \
		SH_CSS_FRAME_FORMAT_NV61, \
		SH_CSS_FRAME_FORMAT_YV12, \
		SH_CSS_FRAME_FORMAT_YV16, \
		SH_CSS_FRAME_FORMAT_YUV420, \
		SH_CSS_FRAME_FORMAT_YUV420_16, \
		SH_CSS_FRAME_FORMAT_YUV422, \
		SH_CSS_FRAME_FORMAT_YUV422_16, \
		SH_CSS_FRAME_FORMAT_YUV_LINE, \
		SH_CSS_FRAME_FORMAT_RAW, \
		SH_CSS_FRAME_FORMAT_UYVY, \
		SH_CSS_FRAME_FORMAT_YUYV, \
		SH_CSS_FRAME_FORMAT_RGB565, \
		SH_CSS_FRAME_FORMAT_PLANAR_RGB888, \
		SH_CSS_FRAME_FORMAT_RGBA888 \
	}

/* GDC */
#define ISP_GDC_BINARY_ID                 SH_CSS_BINARY_ID_GDC
#define ISP_GDC_BINARY                    isp_gdc_var
#define ISP_GDC_MODE                      SH_CSS_BINARY_MODE_GDC
#define ISP_GDC_OUTPUT_NUM_CHUNKS         2
#define ISP_GDC_ENABLE_DS                 0
#define ISP_GDC_ENABLE_FPNR               0
#define ISP_GDC_ENABLE_SC                 0
#define ISP_GDC_ENABLE_S3A                0
#define ISP_GDC_ENABLE_SDIS               0
#define ISP_GDC_ENABLE_VF_VECEVEN         0
#define ISP_GDC_ENABLE_UDS                0
#define ISP_GDC_PIPELINING                1
#define ISP_GDC_DUMMY_BUF_VECTORS         0
#define ISP_GDC_LEFT_CROPPING             0
#define ISP_GDC_TOP_CROPPING              0
#define ISP_GDC_ENABLE_DVS_ENVELOPE       0
#define ISP_GDC_MAX_DVS_ENVELOPE_WIDTH    0
#define ISP_GDC_MAX_DVS_ENVELOPE_HEIGHT   0
#define ISP_GDC_MAX_OUTPUT_WIDTH          SH_CSS_MAX_SENSOR_WIDTH
#define ISP_GDC_MAX_OUTPUT_HEIGHT         SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_GDC_MIN_OUTPUT_WIDTH          SH_CSS_MIN_SENSOR_WIDTH
#define ISP_GDC_MIN_OUTPUT_HEIGHT         SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_GDC_OUTPUT_FORMATS            { SH_CSS_FRAME_FORMAT_YUV420_16 }
#define ISP_GDC_MAX_VF_LOG_DOWNSCALE      0
#define ISP_GDC_INPUT                     SH_CSS_BINARY_INPUT_MEMORY
#define ISP_GDC_C_SUBSAMPLING             SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_GDC_FIXED_S3A_DECI_LOG        0

/* Post ISP */
#define ISP_POST_ISP_BINARY_ID               SH_CSS_BINARY_ID_POST_ISP
#define ISP_POST_ISP_BINARY                  isp_postisp_var
#define ISP_POST_ISP_MODE                    SH_CSS_BINARY_MODE_POST_ISP
#define ISP_POST_ISP_PIPELINING              2
#define ISP_POST_ISP_ENABLE_VF_VECEVEN       1
#define ISP_POST_ISP_ENABLE_DS               0
#define ISP_POST_ISP_ENABLE_FPNR             0
#define ISP_POST_ISP_ENABLE_SC               0
#define ISP_POST_ISP_ENABLE_S3A              0
#define ISP_POST_ISP_ENABLE_SDIS             0
#define ISP_POST_ISP_ENABLE_UDS              0
#define ISP_POST_ISP_OUTPUT_NUM_CHUNKS       2
#define ISP_POST_ISP_DUMMY_BUF_VECTORS       0
#define ISP_POST_ISP_LEFT_CROPPING           SH_CSS_MAX_LEFT_CROPPING
#ifdef SYSTEM_hive_isp_css_2400_system
#define ISP_POST_ISP_TOP_CROPPING            8
#else
#define ISP_POST_ISP_TOP_CROPPING            12
#endif
#define ISP_POST_ISP_ENABLE_DVS_ENVELOPE     0
#define ISP_POST_ISP_MAX_DVS_ENVELOPE_WIDTH  0
#define ISP_POST_ISP_MAX_DVS_ENVELOPE_HEIGHT 0
#define ISP_POST_ISP_MAX_VF_LOG_DOWNSCALE    2
#define ISP_POST_ISP_MAX_OUTPUT_WIDTH        SH_CSS_MAX_SENSOR_WIDTH
#define ISP_POST_ISP_MAX_OUTPUT_HEIGHT       SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_POST_ISP_MIN_OUTPUT_WIDTH        SH_CSS_MIN_SENSOR_WIDTH
#define ISP_POST_ISP_MIN_OUTPUT_HEIGHT       SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_POST_ISP_OUTPUT_FORMATS          SH_CSS_CAPTURE_OUTPUT_FORMATS
#define ISP_POST_ISP_INPUT                   SH_CSS_BINARY_INPUT_MEMORY
#define ISP_POST_ISP_C_SUBSAMPLING           SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_POST_ISP_FIXED_S3A_DECI_LOG      0

/* Pre ISP */
#define ISP_PRE_ISP_BINARY_ID               SH_CSS_BINARY_ID_PRE_ISP
#define ISP_PRE_ISP_BINARY                  isp_preisp_var
#define ISP_PRE_ISP_MODE                    SH_CSS_BINARY_MODE_PRE_ISP
#define ISP_PRE_ISP_ENABLE_FPNR             1
#define ISP_PRE_ISP_ENABLE_SC               1
#define ISP_PRE_ISP_ENABLE_S3A              1
#define ISP_PRE_ISP_ENABLE_SDIS             1
#define ISP_PRE_ISP_ENABLE_DS               0
#define ISP_PRE_ISP_ENABLE_VF_VECEVEN       0
#define ISP_PRE_ISP_ENABLE_UDS              0
#define ISP_PRE_ISP_PIPELINING              1
#define ISP_PRE_ISP_OUTPUT_NUM_CHUNKS       1
#define ISP_PRE_ISP_DUMMY_BUF_VECTORS       0
#define ISP_PRE_ISP_LEFT_CROPPING           0
#define ISP_PRE_ISP_TOP_CROPPING            0
#define ISP_PRE_ISP_ENABLE_DVS_ENVELOPE     0
#define ISP_PRE_ISP_MAX_DVS_ENVELOPE_WIDTH  0
#define ISP_PRE_ISP_MAX_DVS_ENVELOPE_HEIGHT 0
#define ISP_PRE_ISP_MAX_OUTPUT_WIDTH        SH_CSS_MAX_SENSOR_WIDTH
#define ISP_PRE_ISP_MAX_OUTPUT_HEIGHT       SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_PRE_ISP_MIN_OUTPUT_WIDTH        SH_CSS_MIN_SENSOR_WIDTH
#define ISP_PRE_ISP_MIN_OUTPUT_HEIGHT       SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_PRE_ISP_OUTPUT_FORMATS          SH_CSS_PRE_ISP_OUTPUT_FORMATS
#define ISP_PRE_ISP_MAX_VF_LOG_DOWNSCALE    0
#define ISP_PRE_ISP_INPUT                   SH_CSS_BINARY_INPUT_VARIABLE
#define ISP_PRE_ISP_C_SUBSAMPLING           SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_PRE_ISP_FIXED_S3A_DECI_LOG      0

/* ANR */
#define ISP_ANR_BINARY_ID                 SH_CSS_BINARY_ID_ANR
#define ISP_ANR_BINARY                    isp_anr_var
#define ISP_ANR_MODE                      SH_CSS_BINARY_MODE_ANR
#define ISP_ANR_OUTPUT_NUM_CHUNKS         1
#define ISP_ANR_ENABLE_DS                 0
#define ISP_ANR_ENABLE_FPNR               0
#define ISP_ANR_ENABLE_SC                 0
#define ISP_ANR_ENABLE_S3A                0
#define ISP_ANR_ENABLE_SDIS               0
#define ISP_ANR_ENABLE_VF_VECEVEN         0
#define ISP_ANR_ENABLE_UDS                0
#define ISP_ANR_PIPELINING                1
#define ISP_ANR_DUMMY_BUF_VECTORS         0
#define ISP_ANR_LEFT_CROPPING             0
#define ISP_ANR_TOP_CROPPING              0
#define ISP_ANR_ENABLE_DVS_ENVELOPE       0
#define ISP_ANR_MAX_DVS_ENVELOPE_WIDTH    0
#define ISP_ANR_MAX_DVS_ENVELOPE_HEIGHT   0
#define ISP_ANR_MAX_OUTPUT_WIDTH          3840
#define ISP_ANR_MAX_OUTPUT_HEIGHT         SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_ANR_MIN_OUTPUT_WIDTH          SH_CSS_MIN_SENSOR_WIDTH
#define ISP_ANR_MIN_OUTPUT_HEIGHT         SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_ANR_OUTPUT_FORMATS            { SH_CSS_FRAME_FORMAT_RAW }
#define ISP_ANR_MAX_VF_LOG_DOWNSCALE      0
#define ISP_ANR_INPUT                     SH_CSS_BINARY_INPUT_MEMORY
#define ISP_ANR_C_SUBSAMPLING             SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_ANR_FIXED_S3A_DECI_LOG        0

/* Preview DS */
#define ISP_PREVIEW_DS_BINARY_ID               SH_CSS_BINARY_ID_PREVIEW_DS
#define ISP_PREVIEW_DS_BINARY                  isp_preview_ds
#define ISP_PREVIEW_DS_MODE                    SH_CSS_BINARY_MODE_PREVIEW
#define ISP_PREVIEW_DS_OUTPUT_NUM_CHUNKS       2
#define ISP_PREVIEW_DS_DUMMY_BUF_VECTORS       2
#define ISP_PREVIEW_DS_PIPELINING              2
#define ISP_PREVIEW_DS_ENABLE_SC               1
#define ISP_PREVIEW_DS_ENABLE_S3A              1
#define ISP_PREVIEW_DS_ENABLE_VF_VECEVEN       1
#define ISP_PREVIEW_DS_ENABLE_DS               1
#define ISP_PREVIEW_DS_ENABLE_FPNR             0
#define ISP_PREVIEW_DS_ENABLE_SDIS             0
#define ISP_PREVIEW_DS_ENABLE_UDS              0
#define ISP_PREVIEW_DS_LEFT_CROPPING           0
#ifdef SYSTEM_hive_isp_css_2400_system
#define ISP_PREVIEW_DS_TOP_CROPPING            8
#else
#define ISP_PREVIEW_DS_TOP_CROPPING            12
#endif
#define ISP_PREVIEW_DS_ENABLE_DVS_ENVELOPE     0
#define ISP_PREVIEW_DS_MAX_DVS_ENVELOPE_WIDTH  0
#define ISP_PREVIEW_DS_MAX_DVS_ENVELOPE_HEIGHT 0
#define ISP_PREVIEW_DS_MAX_OUTPUT_WIDTH \
	__ISP_MAX_VF_OUTPUT_WIDTH(2*SH_CSS_MAX_VF_WIDTH, \
				  ISP_PREVIEW_DS_LEFT_CROPPING)
#define ISP_PREVIEW_DS_MAX_OUTPUT_HEIGHT       SH_CSS_MAX_VF_HEIGHT
#define ISP_PREVIEW_DS_MIN_OUTPUT_WIDTH        SH_CSS_MIN_SENSOR_WIDTH
#define ISP_PREVIEW_DS_MIN_OUTPUT_HEIGHT       SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_PREVIEW_DS_OUTPUT_FORMATS          { SH_CSS_FRAME_FORMAT_YUV_LINE }
#define ISP_PREVIEW_DS_MAX_VF_LOG_DOWNSCALE    0
#define ISP_PREVIEW_DS_INPUT                   SH_CSS_BINARY_INPUT_SENSOR
#define ISP_PREVIEW_DS_C_SUBSAMPLING           SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_PREVIEW_DS_FIXED_S3A_DECI_LOG      0

/* Preview DZ */
#define ISP_PREVIEW_DZ_BINARY_ID               SH_CSS_BINARY_ID_PREVIEW_DZ
#define ISP_PREVIEW_DZ_BINARY                  isp_preview_var
#define ISP_PREVIEW_DZ_MODE                    SH_CSS_BINARY_MODE_PREVIEW
#define ISP_PREVIEW_DZ_PIPELINING              3
#define ISP_PREVIEW_DZ_LEFT_CROPPING           SH_CSS_MAX_LEFT_CROPPING
#define ISP_PREVIEW_DZ_ENABLE_VF_VECEVEN       1
#define ISP_PREVIEW_DZ_ENABLE_UDS              0
#define ISP_PREVIEW_DZ_ENABLE_SC               1
#define ISP_PREVIEW_DZ_ENABLE_S3A              1
#define ISP_PREVIEW_DZ_ENABLE_DS               0
#define ISP_PREVIEW_DZ_ENABLE_FPNR             0
#define ISP_PREVIEW_DZ_ENABLE_SDIS             0
#define ISP_PREVIEW_DZ_OUTPUT_NUM_CHUNKS       1
#define ISP_PREVIEW_DZ_DUMMY_BUF_VECTORS       0
#ifdef SYSTEM_hive_isp_css_2400_system
#define ISP_PREVIEW_DZ_TOP_CROPPING            8
#else
#define ISP_PREVIEW_DZ_TOP_CROPPING            12
#endif
#define ISP_PREVIEW_DZ_ENABLE_DVS_ENVELOPE     0
#define ISP_PREVIEW_DZ_MAX_DVS_ENVELOPE_WIDTH  0
#define ISP_PREVIEW_DZ_MAX_DVS_ENVELOPE_HEIGHT 0
#define ISP_PREVIEW_DZ_MAX_OUTPUT_WIDTH \
	__ISP_MAX_VF_OUTPUT_WIDTH(2*SH_CSS_MAX_VF_WIDTH, \
				  ISP_PREVIEW_DZ_LEFT_CROPPING)
#define ISP_PREVIEW_DZ_MAX_OUTPUT_HEIGHT       SH_CSS_MAX_VF_HEIGHT
#define ISP_PREVIEW_DZ_MIN_OUTPUT_WIDTH        SH_CSS_MIN_SENSOR_WIDTH
#define ISP_PREVIEW_DZ_MIN_OUTPUT_HEIGHT       SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_PREVIEW_DZ_OUTPUT_FORMATS          { SH_CSS_FRAME_FORMAT_YUV_LINE }
#define ISP_PREVIEW_DZ_MAX_VF_LOG_DOWNSCALE    0
#define ISP_PREVIEW_DZ_INPUT                   SH_CSS_BINARY_INPUT_VARIABLE
#define ISP_PREVIEW_DZ_C_SUBSAMPLING           SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_PREVIEW_DZ_FIXED_S3A_DECI_LOG      0

/* Primary 14MP */
#define ISP_PRIMARY_14MP_BINARY_ID               SH_CSS_BINARY_ID_PRIMARY_14MP
#define ISP_PRIMARY_14MP_BINARY                  isp_primary_14mp
#define ISP_PRIMARY_14MP_MODE                    SH_CSS_BINARY_MODE_PRIMARY
#define ISP_PRIMARY_14MP_VF_LOG_DOWNSCALE        2
#define ISP_PRIMARY_14MP_LEFT_CROPPING           SH_CSS_MAX_LEFT_CROPPING
#define ISP_PRIMARY_14MP_PIPELINING              4
#define ISP_PRIMARY_14MP_ENABLE_VF_VECEVEN       1
#define ISP_PRIMARY_14MP_ENABLE_FPNR             1
#define ISP_PRIMARY_14MP_ENABLE_SC               1
#define ISP_PRIMARY_14MP_ENABLE_S3A              1
#define ISP_PRIMARY_14MP_ENABLE_DS               0
#define ISP_PRIMARY_14MP_ENABLE_SDIS             0
#define ISP_PRIMARY_14MP_ENABLE_UDS              0
#define ISP_PRIMARY_14MP_OUTPUT_NUM_CHUNKS       1
#define ISP_PRIMARY_14MP_DUMMY_BUF_VECTORS       0
#ifdef SYSTEM_hive_isp_css_2400_system
#define ISP_PRIMARY_14MP_TOP_CROPPING            8
#else
#define ISP_PRIMARY_14MP_TOP_CROPPING            12
#endif
#define ISP_PRIMARY_14MP_ENABLE_DVS_ENVELOPE     0
#define ISP_PRIMARY_14MP_MAX_DVS_ENVELOPE_WIDTH  0
#define ISP_PRIMARY_14MP_MAX_DVS_ENVELOPE_HEIGHT 0
#define ISP_PRIMARY_14MP_MAX_OUTPUT_WIDTH        4352
#define ISP_PRIMARY_14MP_MAX_OUTPUT_HEIGHT       SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_PRIMARY_14MP_MIN_OUTPUT_WIDTH     ISP_PRIMARY_14MP_MAX_OUTPUT_WIDTH
#define ISP_PRIMARY_14MP_MIN_OUTPUT_HEIGHT    ISP_PRIMARY_14MP_MAX_OUTPUT_HEIGHT
#define ISP_PRIMARY_14MP_OUTPUT_FORMATS       { SH_CSS_FIXED_PRIMARY_FORMAT }
#define ISP_PRIMARY_14MP_MAX_VF_LOG_DOWNSCALE ISP_PRIMARY_14MP_VF_LOG_DOWNSCALE
#define ISP_PRIMARY_14MP_INPUT                SH_CSS_BINARY_INPUT_SENSOR
#define ISP_PRIMARY_14MP_C_SUBSAMPLING        1
#define ISP_PRIMARY_14MP_FIXED_S3A_DECI_LOG   6

/* Primary 16MP */
#define ISP_PRIMARY_16MP_BINARY_ID           SH_CSS_BINARY_ID_PRIMARY_16MP
#define ISP_PRIMARY_16MP_BINARY              isp_primary_16mp
#define ISP_PRIMARY_16MP_MODE                SH_CSS_BINARY_MODE_PRIMARY
#define ISP_PRIMARY_16MP_VF_LOG_DOWNSCALE    2
#define ISP_PRIMARY_16MP_PIPELINING          4
#define ISP_PRIMARY_16MP_ENABLE_FPNR         1
#define ISP_PRIMARY_16MP_ENABLE_SC           1
#define ISP_PRIMARY_16MP_ENABLE_S3A          1
#define ISP_PRIMARY_16MP_ENABLE_VF_VECEVEN   1
#define ISP_PRIMARY_16MP_ENABLE_DS           0
#define ISP_PRIMARY_16MP_ENABLE_SDIS         0
#define ISP_PRIMARY_16MP_ENABLE_UDS          0
#define ISP_PRIMARY_16MP_OUTPUT_NUM_CHUNKS   1
#define ISP_PRIMARY_16MP_DUMMY_BUF_VECTORS   0
#define ISP_PRIMARY_16MP_LEFT_CROPPING       0
#ifdef SYSTEM_hive_isp_css_2400_system
#define ISP_PRIMARY_16MP_TOP_CROPPING        8
#else
#define ISP_PRIMARY_16MP_TOP_CROPPING        12
#endif
#define ISP_PRIMARY_16MP_ENABLE_DVS_ENVELOPE 0
#define ISP_PRIMARY_16MP_MAX_DVS_ENVELOPE_WIDTH   0
#define ISP_PRIMARY_16MP_MAX_DVS_ENVELOPE_HEIGHT  0
#define ISP_PRIMARY_16MP_MAX_OUTPUT_WIDTH    4608
#define ISP_PRIMARY_16MP_MAX_OUTPUT_HEIGHT   SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_PRIMARY_16MP_MIN_OUTPUT_WIDTH    ISP_PRIMARY_16MP_MAX_OUTPUT_WIDTH
#define ISP_PRIMARY_16MP_MIN_OUTPUT_HEIGHT   ISP_PRIMARY_16MP_MAX_OUTPUT_HEIGHT
#define ISP_PRIMARY_16MP_OUTPUT_FORMATS      { SH_CSS_FIXED_PRIMARY_FORMAT }
#define ISP_PRIMARY_16MP_MAX_VF_LOG_DOWNSCALE ISP_PRIMARY_16MP_VF_LOG_DOWNSCALE
#define ISP_PRIMARY_16MP_INPUT                SH_CSS_BINARY_INPUT_SENSOR
#define ISP_PRIMARY_16MP_C_SUBSAMPLING        1
#define ISP_PRIMARY_16MP_FIXED_S3A_DECI_LOG   6

/* Primary 8MP */
#define ISP_PRIMARY_8MP_BINARY_ID           SH_CSS_BINARY_ID_PRIMARY_8MP
#define ISP_PRIMARY_8MP_BINARY              isp_primary_8mp
#define ISP_PRIMARY_8MP_MODE                SH_CSS_BINARY_MODE_PRIMARY
#define ISP_PRIMARY_8MP_VF_LOG_DOWNSCALE    1
#define ISP_PRIMARY_8MP_LEFT_CROPPING       SH_CSS_MAX_LEFT_CROPPING
#define ISP_PRIMARY_8MP_PIPELINING          4
#define ISP_PRIMARY_8MP_ENABLE_FPNR         1
#define ISP_PRIMARY_8MP_ENABLE_SC           1
#define ISP_PRIMARY_8MP_ENABLE_S3A          1
#define ISP_PRIMARY_8MP_ENABLE_VF_VECEVEN   1
#define ISP_PRIMARY_8MP_ENABLE_DS           0
#define ISP_PRIMARY_8MP_ENABLE_SDIS         0
#define ISP_PRIMARY_8MP_ENABLE_UDS          0
#define ISP_PRIMARY_8MP_OUTPUT_NUM_CHUNKS   1
#define ISP_PRIMARY_8MP_DUMMY_BUF_VECTORS   0
#ifdef SYSTEM_hive_isp_css_2400_system
#define ISP_PRIMARY_8MP_TOP_CROPPING        8
#else
#define ISP_PRIMARY_8MP_TOP_CROPPING        12
#endif
#define ISP_PRIMARY_8MP_ENABLE_DVS_ENVELOPE 0
#define ISP_PRIMARY_8MP_MAX_DVS_ENVELOPE_WIDTH   0
#define ISP_PRIMARY_8MP_MAX_DVS_ENVELOPE_HEIGHT  0
#define ISP_PRIMARY_8MP_MAX_OUTPUT_WIDTH    3264
#define ISP_PRIMARY_8MP_MAX_OUTPUT_HEIGHT   SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_PRIMARY_8MP_MIN_OUTPUT_WIDTH    ISP_PRIMARY_8MP_MAX_OUTPUT_WIDTH
#define ISP_PRIMARY_8MP_MIN_OUTPUT_HEIGHT   ISP_PRIMARY_8MP_MAX_OUTPUT_HEIGHT
#define ISP_PRIMARY_8MP_OUTPUT_FORMATS      { SH_CSS_FIXED_PRIMARY_FORMAT }
#define ISP_PRIMARY_8MP_MAX_VF_LOG_DOWNSCALE ISP_PRIMARY_8MP_VF_LOG_DOWNSCALE
#define ISP_PRIMARY_8MP_INPUT                SH_CSS_BINARY_INPUT_SENSOR
#define ISP_PRIMARY_8MP_C_SUBSAMPLING        1
#define ISP_PRIMARY_8MP_FIXED_S3A_DECI_LOG   6

/* Primary DS */
#define ISP_PRIMARY_DS_BINARY_ID            SH_CSS_BINARY_ID_PRIMARY_DS
#define ISP_PRIMARY_DS_BINARY               isp_primary_ds
#define ISP_PRIMARY_DS_MODE                 SH_CSS_BINARY_MODE_PRIMARY
#define ISP_PRIMARY_DS_OUTPUT_NUM_CHUNKS    2
#define ISP_PRIMARY_DS_DUMMY_BUF_VECTORS    2
#define ISP_PRIMARY_DS_PIPELINING           2
#define ISP_PRIMARY_DS_ENABLE_FPNR          1
#define ISP_PRIMARY_DS_ENABLE_SC            1
#define ISP_PRIMARY_DS_ENABLE_S3A           1
#define ISP_PRIMARY_DS_ENABLE_VF_VECEVEN    1
#define ISP_PRIMARY_DS_ENABLE_DS            1
#define ISP_PRIMARY_DS_ENABLE_SDIS          0
#define ISP_PRIMARY_DS_ENABLE_UDS           0
#define ISP_PRIMARY_DS_LEFT_CROPPING        0
#ifdef SYSTEM_hive_isp_css_2400_system
#define ISP_PRIMARY_DS_TOP_CROPPING         8
#else
#define ISP_PRIMARY_DS_TOP_CROPPING         12
#endif
#define ISP_PRIMARY_DS_ENABLE_DVS_ENVELOPE  0
#define ISP_PRIMARY_DS_MAX_DVS_ENVELOPE_WIDTH   0
#define ISP_PRIMARY_DS_MAX_DVS_ENVELOPE_HEIGHT  0
#define ISP_PRIMARY_DS_MAX_OUTPUT_WIDTH     2560
#define ISP_PRIMARY_DS_MAX_OUTPUT_HEIGHT    1920
#define ISP_PRIMARY_DS_MIN_OUTPUT_WIDTH     SH_CSS_MIN_SENSOR_WIDTH
#define ISP_PRIMARY_DS_MIN_OUTPUT_HEIGHT    SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_PRIMARY_DS_OUTPUT_FORMATS       SH_CSS_CAPTURE_DS_OUTPUT_FORMATS
#define ISP_PRIMARY_DS_MAX_VF_LOG_DOWNSCALE 1
#define ISP_PRIMARY_DS_INPUT                SH_CSS_BINARY_INPUT_VARIABLE
#define ISP_PRIMARY_DS_C_SUBSAMPLING        SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_PRIMARY_DS_FIXED_S3A_DECI_LOG   0

#ifdef SYSTEM_hive_isp_css_2400_system
/* Primary Small */
#define ISP_PRIMARY_SMALL_BINARY_ID           SH_CSS_BINARY_ID_PRIMARY_SMALL
#define ISP_PRIMARY_SMALL_BINARY              isp_primary_small
#define ISP_PRIMARY_SMALL_MODE                SH_CSS_BINARY_MODE_PRIMARY
#define ISP_PRIMARY_SMALL_LEFT_CROPPING       SH_CSS_MAX_LEFT_CROPPING
#define ISP_PRIMARY_SMALL_PIPELINING          2
#define ISP_PRIMARY_SMALL_ENABLE_FPNR         1
#define ISP_PRIMARY_SMALL_ENABLE_SC           1
#define ISP_PRIMARY_SMALL_ENABLE_S3A          1
#define ISP_PRIMARY_SMALL_ENABLE_VF_VECEVEN   1
#define ISP_PRIMARY_SMALL_ENABLE_DS           0
#define ISP_PRIMARY_SMALL_ENABLE_SDIS         0
#define ISP_PRIMARY_SMALL_ENABLE_UDS          0
#define ISP_PRIMARY_SMALL_OUTPUT_NUM_CHUNKS   1
#define ISP_PRIMARY_SMALL_DUMMY_BUF_VECTORS   0
#define ISP_PRIMARY_SMALL_TOP_CROPPING        8
#define ISP_PRIMARY_SMALL_ENABLE_DVS_ENVELOPE 0
#define ISP_PRIMARY_SMALL_MAX_DVS_ENVELOPE_WIDTH   0
#define ISP_PRIMARY_SMALL_MAX_DVS_ENVELOPE_HEIGHT  0
#define ISP_PRIMARY_SMALL_MAX_OUTPUT_WIDTH    2560
#define ISP_PRIMARY_SMALL_MAX_OUTPUT_HEIGHT   1920
#define ISP_PRIMARY_SMALL_MIN_OUTPUT_WIDTH    SH_CSS_MIN_SENSOR_WIDTH
#define ISP_PRIMARY_SMALL_MIN_OUTPUT_HEIGHT   SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_PRIMARY_SMALL_OUTPUT_FORMATS      SH_CSS_CAPTURE_OUTPUT_FORMATS
#define ISP_PRIMARY_SMALL_MAX_VF_LOG_DOWNSCALE 1
#define ISP_PRIMARY_SMALL_INPUT                SH_CSS_BINARY_INPUT_VARIABLE
#define ISP_PRIMARY_SMALL_C_SUBSAMPLING        SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_PRIMARY_SMALL_FIXED_S3A_DECI_LOG   0
#else
/* Primary Small */
#define ISP_PRIMARY_SMALL_BINARY_ID           SH_CSS_BINARY_ID_PRIMARY_SMALL
#define ISP_PRIMARY_SMALL_BINARY              isp_primary_small
#define ISP_PRIMARY_SMALL_MODE                SH_CSS_BINARY_MODE_PRIMARY
#define ISP_PRIMARY_SMALL_LEFT_CROPPING       SH_CSS_MAX_LEFT_CROPPING
#define ISP_PRIMARY_SMALL_PIPELINING          3
#define ISP_PRIMARY_SMALL_ENABLE_FPNR         1
#define ISP_PRIMARY_SMALL_ENABLE_SC           1
#define ISP_PRIMARY_SMALL_ENABLE_S3A          1
#define ISP_PRIMARY_SMALL_ENABLE_VF_VECEVEN   1
#define ISP_PRIMARY_SMALL_ENABLE_DS           0
#define ISP_PRIMARY_SMALL_ENABLE_SDIS         0
#define ISP_PRIMARY_SMALL_ENABLE_UDS          0
#define ISP_PRIMARY_SMALL_OUTPUT_NUM_CHUNKS   2
#define ISP_PRIMARY_SMALL_DUMMY_BUF_VECTORS   0
#ifdef SYSTEM_hive_isp_css_2400_system
#define ISP_PRIMARY_SMALL_TOP_CROPPING        8
#else
#define ISP_PRIMARY_SMALL_TOP_CROPPING        12
#endif
#define ISP_PRIMARY_SMALL_ENABLE_DVS_ENVELOPE 0
#define ISP_PRIMARY_SMALL_MAX_DVS_ENVELOPE_WIDTH   0
#define ISP_PRIMARY_SMALL_MAX_DVS_ENVELOPE_HEIGHT  0
#define ISP_PRIMARY_SMALL_MAX_OUTPUT_WIDTH    3264
#define ISP_PRIMARY_SMALL_MAX_OUTPUT_HEIGHT   SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_PRIMARY_SMALL_MIN_OUTPUT_WIDTH    SH_CSS_MIN_SENSOR_WIDTH
#define ISP_PRIMARY_SMALL_MIN_OUTPUT_HEIGHT   SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_PRIMARY_SMALL_OUTPUT_FORMATS      SH_CSS_YUV422_OUTPUT_FORMATS
#define ISP_PRIMARY_SMALL_MAX_VF_LOG_DOWNSCALE 2
#define ISP_PRIMARY_SMALL_INPUT                SH_CSS_BINARY_INPUT_VARIABLE
#define ISP_PRIMARY_SMALL_C_SUBSAMPLING        SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_PRIMARY_SMALL_FIXED_S3A_DECI_LOG   0
#endif

/* Primary Var */
#define ISP_PRIMARY_VAR_BINARY_ID           SH_CSS_BINARY_ID_PRIMARY_VAR
#define ISP_PRIMARY_VAR_BINARY              isp_primary_var
#define ISP_PRIMARY_VAR_MODE                SH_CSS_BINARY_MODE_PRIMARY
#define ISP_PRIMARY_VAR_OUTPUT_NUM_CHUNKS   4
#define ISP_PRIMARY_VAR_LEFT_CROPPING       SH_CSS_MAX_LEFT_CROPPING
#define ISP_PRIMARY_VAR_PIPELINING          3
#define ISP_PRIMARY_VAR_ENABLE_FPNR         1
#define ISP_PRIMARY_VAR_ENABLE_SC           1
#define ISP_PRIMARY_VAR_ENABLE_S3A          1
#define ISP_PRIMARY_VAR_ENABLE_VF_VECEVEN   1
#define ISP_PRIMARY_VAR_ENABLE_DS           0
#define ISP_PRIMARY_VAR_ENABLE_SDIS         0
#define ISP_PRIMARY_VAR_ENABLE_UDS          0
#define ISP_PRIMARY_VAR_DUMMY_BUF_VECTORS   0
#ifdef SYSTEM_hive_isp_css_2400_system
#define ISP_PRIMARY_VAR_TOP_CROPPING        8
#else
#define ISP_PRIMARY_VAR_TOP_CROPPING        12
#endif
#define ISP_PRIMARY_VAR_ENABLE_DVS_ENVELOPE 0
#define ISP_PRIMARY_VAR_MAX_DVS_ENVELOPE_WIDTH   0
#define ISP_PRIMARY_VAR_MAX_DVS_ENVELOPE_HEIGHT  0
#define ISP_PRIMARY_VAR_MAX_VF_LOG_DOWNSCALE     2
#define ISP_PRIMARY_VAR_MAX_OUTPUT_WIDTH    SH_CSS_MAX_SENSOR_WIDTH
#define ISP_PRIMARY_VAR_MAX_OUTPUT_HEIGHT   SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_PRIMARY_VAR_MIN_OUTPUT_WIDTH    SH_CSS_MIN_SENSOR_WIDTH
#define ISP_PRIMARY_VAR_MIN_OUTPUT_HEIGHT   SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_PRIMARY_VAR_OUTPUT_FORMATS      SH_CSS_CAPTURE_OUTPUT_FORMATS
#define ISP_PRIMARY_VAR_INPUT               SH_CSS_BINARY_INPUT_VARIABLE
#define ISP_PRIMARY_VAR_C_SUBSAMPLING       SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_PRIMARY_VAR_FIXED_S3A_DECI_LOG  0

/* Primary Ref */
#define ISP_PRIMARY_REF_BINARY_ID           SH_CSS_BINARY_ID_PRIMARY_REF
#define ISP_PRIMARY_REF_BINARY              isp_primary_ref
#define ISP_PRIMARY_REF_MODE                SH_CSS_BINARY_MODE_PRIMARY
#define ISP_PRIMARY_REF_VF_LOG_DOWNSCALE    1
#define ISP_PRIMARY_REF_LEFT_CROPPING       SH_CSS_MAX_LEFT_CROPPING
#define ISP_PRIMARY_REF_PIPELINING          4
#define ISP_PRIMARY_REF_ENABLE_FPNR         1
#define ISP_PRIMARY_REF_ENABLE_SC           1
#define ISP_PRIMARY_REF_ENABLE_S3A          1
#define ISP_PRIMARY_REF_ENABLE_VF_VECEVEN   1
#define ISP_PRIMARY_REF_ENABLE_DS           0
#define ISP_PRIMARY_REF_ENABLE_SDIS         0
#define ISP_PRIMARY_REF_ENABLE_UDS          0
#define ISP_PRIMARY_REF_OUTPUT_NUM_CHUNKS   1
#define ISP_PRIMARY_REF_DUMMY_BUF_VECTORS   0
#ifdef SYSTEM_hive_isp_css_2400_system
#define ISP_PRIMARY_REF_TOP_CROPPING        8
#else
#define ISP_PRIMARY_REF_TOP_CROPPING        12
#endif
#define ISP_PRIMARY_REF_ENABLE_DVS_ENVELOPE 0
#define ISP_PRIMARY_REF_MAX_DVS_ENVELOPE_WIDTH   0
#define ISP_PRIMARY_REF_MAX_DVS_ENVELOPE_HEIGHT  0
/*
#define ISP_PRIMARY_REF_MAX_OUTPUT_WIDTH    SH_CSS_MAX_SENSOR_WIDTH
#define ISP_PRIMARY_REF_MAX_OUTPUT_HEIGHT   SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_PRIMARY_REF_MIN_OUTPUT_WIDTH    SH_CSS_MIN_SENSOR_WIDTH
#define ISP_PRIMARY_REF_MIN_OUTPUT_HEIGHT   SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_PRIMARY_REF_OUTPUT_FORMATS      SH_CSS_CAPTURE_OUTPUT_FORMATS
#define ISP_PRIMARY_REF_INPUT               SH_CSS_BINARY_INPUT_VARIABLE
#define ISP_PRIMARY_REF_C_SUBSAMPLING       SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_PRIMARY_REF_FIXED_S3A_DECI_LOG  0
*/
#define ISP_PRIMARY_REF_MAX_OUTPUT_WIDTH    3328
#define ISP_PRIMARY_REF_MAX_OUTPUT_HEIGHT   SH_CSS_MAX_SENSOR_HEIGHT
#define ISP_PRIMARY_REF_MIN_OUTPUT_WIDTH    ISP_PRIMARY_REF_MAX_OUTPUT_WIDTH
#define ISP_PRIMARY_REF_MIN_OUTPUT_HEIGHT   ISP_PRIMARY_REF_MAX_OUTPUT_HEIGHT
#define ISP_PRIMARY_REF_OUTPUT_FORMATS      { SH_CSS_FIXED_PRIMARY_FORMAT }
#define ISP_PRIMARY_REF_MAX_VF_LOG_DOWNSCALE ISP_PRIMARY_REF_VF_LOG_DOWNSCALE
#define ISP_PRIMARY_REF_INPUT                SH_CSS_BINARY_INPUT_SENSOR
#define ISP_PRIMARY_REF_C_SUBSAMPLING        1
#define ISP_PRIMARY_REF_FIXED_S3A_DECI_LOG   6

/* Video Offline */
#define ISP_VIDEO_OFFLINE_BINARY_ID           SH_CSS_BINARY_ID_VIDEO_OFFLINE
#define ISP_VIDEO_OFFLINE_BINARY              isp_video_offline
#define ISP_VIDEO_OFFLINE_MODE                SH_CSS_BINARY_MODE_VIDEO
#define ISP_VIDEO_OFFLINE_PIPELINING          3
/* we use the VF_VECEVEN dma channel for the input frame so
 * we cannot generate viewfinder output here. This is also not
 * needed for the demo. */
#define ISP_VIDEO_OFFLINE_ENABLE_VF_VECEVEN   0
#define ISP_VIDEO_OFFLINE_ENABLE_SC           1
#define ISP_VIDEO_OFFLINE_ENABLE_S3A          1
#define ISP_VIDEO_OFFLINE_ENABLE_SDIS         1
#define ISP_VIDEO_OFFLINE_ENABLE_DVS_ENVELOPE 0
#define ISP_VIDEO_OFFLINE_ENABLE_UDS          0
#define ISP_VIDEO_OFFLINE_ENABLE_DS           0
#define ISP_VIDEO_OFFLINE_ENABLE_FPNR         0
#define ISP_VIDEO_OFFLINE_OUTPUT_NUM_CHUNKS   1
#define ISP_VIDEO_OFFLINE_DUMMY_BUF_VECTORS   0
#define ISP_VIDEO_OFFLINE_LEFT_CROPPING       0
#ifdef SYSTEM_hive_isp_css_2400_system
#define ISP_VIDEO_OFFLINE_TOP_CROPPING        8
#else
#define ISP_VIDEO_OFFLINE_TOP_CROPPING        12
#endif
#define ISP_VIDEO_OFFLINE_MAX_DVS_ENVELOPE_WIDTH   0
#define ISP_VIDEO_OFFLINE_MAX_DVS_ENVELOPE_HEIGHT  0
#define ISP_VIDEO_OFFLINE_MAX_OUTPUT_WIDTH    1920
#define ISP_VIDEO_OFFLINE_MAX_OUTPUT_HEIGHT   1080
#define ISP_VIDEO_OFFLINE_MIN_OUTPUT_WIDTH    SH_CSS_MIN_SENSOR_WIDTH
#define ISP_VIDEO_OFFLINE_MIN_OUTPUT_HEIGHT   SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_VIDEO_OFFLINE_OUTPUT_FORMATS      SH_CSS_VIDEO_OUTPUT_FORMATS
#define ISP_VIDEO_OFFLINE_MAX_VF_LOG_DOWNSCALE 1
#define ISP_VIDEO_OFFLINE_INPUT               SH_CSS_BINARY_INPUT_MEMORY
#define ISP_VIDEO_OFFLINE_C_SUBSAMPLING       SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_VIDEO_OFFLINE_FIXED_S3A_DECI_LOG  0

/* Video Online DZ */
#define ISP_VIDEO_DZ_BINARY_ID               SH_CSS_BINARY_ID_VIDEO_DZ
#define ISP_VIDEO_DZ_BINARY                  isp_video_dz
#define ISP_VIDEO_DZ_MODE                    SH_CSS_BINARY_MODE_VIDEO
#define ISP_VIDEO_DZ_OUTPUT_NUM_CHUNKS       2
#define ISP_VIDEO_DZ_PIPELINING              3
#define ISP_VIDEO_DZ_MAX_DVS_ENVELOPE_WIDTH  384
#define ISP_VIDEO_DZ_MAX_DVS_ENVELOPE_HEIGHT 216
#define ISP_VIDEO_DZ_ENABLE_SC               1
#define ISP_VIDEO_DZ_ENABLE_S3A              1
#define ISP_VIDEO_DZ_ENABLE_SDIS             1
#define ISP_VIDEO_DZ_ENABLE_DVS_ENVELOPE     1
#define ISP_VIDEO_DZ_ENABLE_UDS              1
#define ISP_VIDEO_DZ_ENABLE_VF_VECEVEN       1
#define ISP_VIDEO_DZ_ENABLE_DS               0
#define ISP_VIDEO_DZ_ENABLE_FPNR             0
#define ISP_VIDEO_DZ_DUMMY_BUF_VECTORS       0
#define ISP_VIDEO_DZ_LEFT_CROPPING           0
#define ISP_VIDEO_DZ_TOP_CROPPING            0
#define ISP_VIDEO_DZ_MAX_OUTPUT_WIDTH        1920
#define ISP_VIDEO_DZ_MAX_OUTPUT_HEIGHT       1080
#define ISP_VIDEO_DZ_MIN_OUTPUT_WIDTH        SH_CSS_MIN_SENSOR_WIDTH
#define ISP_VIDEO_DZ_MIN_OUTPUT_HEIGHT       SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_VIDEO_DZ_OUTPUT_FORMATS          SH_CSS_VIDEO_OUTPUT_FORMATS
#define ISP_VIDEO_DZ_MAX_VF_LOG_DOWNSCALE    1
#define ISP_VIDEO_DZ_INPUT                   SH_CSS_BINARY_INPUT_SENSOR
#define ISP_VIDEO_DZ_C_SUBSAMPLING           SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_VIDEO_DZ_FIXED_S3A_DECI_LOG      0

/* Video Online DS */
#define ISP_VIDEO_DS_BINARY_ID            SH_CSS_BINARY_ID_VIDEO_DS
#define ISP_VIDEO_DS_BINARY               isp_video_ds
#define ISP_VIDEO_DS_MODE                 SH_CSS_BINARY_MODE_VIDEO
#define ISP_VIDEO_DS_OUTPUT_NUM_CHUNKS    2
#define ISP_VIDEO_DS_DUMMY_BUF_VECTORS    2
#define ISP_VIDEO_DS_PIPELINING           2
#define ISP_VIDEO_DS_ENABLE_SC            1
#define ISP_VIDEO_DS_ENABLE_S3A           1
#define ISP_VIDEO_DS_ENABLE_SDIS          0
#define ISP_VIDEO_DS_ENABLE_DVS_ENVELOPE  1
#define ISP_VIDEO_DS_ENABLE_VF_VECEVEN    1
#define ISP_VIDEO_DS_ENABLE_DS            1
#define ISP_VIDEO_DS_ENABLE_FPNR          0
#define ISP_VIDEO_DS_ENABLE_UDS           0
#define ISP_VIDEO_DS_LEFT_CROPPING        0
#ifdef SYSTEM_hive_isp_css_2400_system
#define ISP_VIDEO_DS_TOP_CROPPING         8
#else
#define ISP_VIDEO_DS_TOP_CROPPING         12
#endif
#define ISP_VIDEO_DS_MAX_DVS_ENVELOPE_WIDTH   0
#define ISP_VIDEO_DS_MAX_DVS_ENVELOPE_HEIGHT  0
#define ISP_VIDEO_DS_MAX_OUTPUT_WIDTH     1920
#define ISP_VIDEO_DS_MAX_OUTPUT_HEIGHT    1080
#define ISP_VIDEO_DS_MIN_OUTPUT_WIDTH     SH_CSS_MIN_SENSOR_WIDTH
#define ISP_VIDEO_DS_MIN_OUTPUT_HEIGHT    SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_VIDEO_DS_OUTPUT_FORMATS       SH_CSS_VIDEO_OUTPUT_FORMATS
#define ISP_VIDEO_DS_MAX_VF_LOG_DOWNSCALE 1
#define ISP_VIDEO_DS_INPUT                SH_CSS_BINARY_INPUT_SENSOR
#define ISP_VIDEO_DS_C_SUBSAMPLING        SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_VIDEO_DS_FIXED_S3A_DECI_LOG   0

/* Video Online no DZ */
#define ISP_VIDEO_NODZ_BINARY_ID                SH_CSS_BINARY_ID_VIDEO_NODZ
#define ISP_VIDEO_NODZ_BINARY                   isp_video_nodz
#define ISP_VIDEO_NODZ_MODE                     SH_CSS_BINARY_MODE_VIDEO
#define ISP_VIDEO_NODZ_PIPELINING               3
#define ISP_VIDEO_NODZ_MAX_DVS_ENVELOPE_WIDTH   384
#define ISP_VIDEO_NODZ_MAX_DVS_ENVELOPE_HEIGHT  216
#define ISP_VIDEO_NODZ_ENABLE_SC                1
#define ISP_VIDEO_NODZ_ENABLE_S3A               1
#define ISP_VIDEO_NODZ_ENABLE_SDIS              1
#define ISP_VIDEO_NODZ_ENABLE_DVS_ENVELOPE      1
#define ISP_VIDEO_NODZ_ENABLE_VF_VECEVEN        1
#define ISP_VIDEO_NODZ_ENABLE_DS                0
#define ISP_VIDEO_NODZ_ENABLE_FPNR              0
#define ISP_VIDEO_NODZ_ENABLE_UDS               0
#define ISP_VIDEO_NODZ_OUTPUT_NUM_CHUNKS        2
#define ISP_VIDEO_NODZ_DUMMY_BUF_VECTORS        0
#define ISP_VIDEO_NODZ_LEFT_CROPPING            0
#define ISP_VIDEO_NODZ_TOP_CROPPING             0
#define ISP_VIDEO_NODZ_MAX_OUTPUT_WIDTH         1920
#define ISP_VIDEO_NODZ_MAX_OUTPUT_HEIGHT        1080
#define ISP_VIDEO_NODZ_MIN_OUTPUT_WIDTH         SH_CSS_MIN_SENSOR_WIDTH
#define ISP_VIDEO_NODZ_MIN_OUTPUT_HEIGHT        SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_VIDEO_NODZ_OUTPUT_FORMATS           SH_CSS_VIDEO_OUTPUT_FORMATS
#define ISP_VIDEO_NODZ_MAX_VF_LOG_DOWNSCALE     1
#define ISP_VIDEO_NODZ_INPUT                    SH_CSS_BINARY_INPUT_SENSOR
#define ISP_VIDEO_NODZ_C_SUBSAMPLING            SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_VIDEO_NODZ_FIXED_S3A_DECI_LOG       0

/* Viewfinder Post-processing */
#define ISP_VF_PP_BINARY_ID             SH_CSS_BINARY_ID_VF_PP
#define ISP_VF_PP_BINARY                isp_vf_pp
#define ISP_VF_PP_MODE                  SH_CSS_BINARY_MODE_VF_PP
#define ISP_VF_PP_ENABLE_DS             1
#define ISP_VF_PP_ENABLE_FPNR           0
#define ISP_VF_PP_ENABLE_SC             0
#define ISP_VF_PP_ENABLE_S3A            0
#define ISP_VF_PP_ENABLE_SDIS           0
#define ISP_VF_PP_ENABLE_VF_VECEVEN     0
#define ISP_VF_PP_ENABLE_UDS            0
#define ISP_VF_PP_PIPELINING            1
#define ISP_VF_PP_OUTPUT_NUM_CHUNKS     1
#define ISP_VF_PP_DUMMY_BUF_VECTORS     0
#define ISP_VF_PP_LEFT_CROPPING         0
#define ISP_VF_PP_TOP_CROPPING          0
#define ISP_VF_PP_ENABLE_DVS_ENVELOPE   0
#define ISP_VF_PP_MAX_DVS_ENVELOPE_WIDTH   0
#define ISP_VF_PP_MAX_DVS_ENVELOPE_HEIGHT  0
#define ISP_VF_PP_MAX_OUTPUT_WIDTH         SH_CSS_MAX_VF_WIDTH
#define ISP_VF_PP_MAX_OUTPUT_HEIGHT        SH_CSS_MAX_VF_HEIGHT
#define ISP_VF_PP_MIN_OUTPUT_WIDTH         SH_CSS_MIN_SENSOR_WIDTH
#define ISP_VF_PP_MIN_OUTPUT_HEIGHT        SH_CSS_MIN_SENSOR_HEIGHT
#define ISP_VF_PP_OUTPUT_FORMATS           SH_CSS_VF_OUTPUT_FORMATS
#define ISP_VF_PP_MAX_VF_LOG_DOWNSCALE     0
#define ISP_VF_PP_INPUT                    SH_CSS_BINARY_INPUT_MEMORY
#define ISP_VF_PP_C_SUBSAMPLING            SH_CSS_DEFAULT_C_SUBSAMPLING
#define ISP_VF_PP_FIXED_S3A_DECI_LOG       0

#endif /* _SH_CSS_BINARY_INFO_H_ */
