/*
 * Support for Medfield PNW Camera Imaging ISP subsystem.
 *
 * Copyright (c) 2010 Intel Corporation. All Rights Reserved.
 *
 * Copyright (c) 2010 Silicon Hive www.siliconhive.com.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version
 * 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 *
 */

#ifndef _SP_MAP_H_
#define _SP_MAP_H_


#ifndef _hrt_dummy_use_blob_sp
#define _hrt_dummy_use_blob_sp()
#endif

#define _hrt_cell_load_program_sp(proc) \
	_hrt_cell_load_program_from_elf_file(proc, "sp")

#define HIVE_MEM_isp_vectors_per_input_line  scalar_processor_dmem
#define HIVE_ADDR_isp_vectors_per_input_line 0xF38
#define HIVE_SIZE_isp_vectors_per_input_line 4
#define HIVE_MEM_sp_raw_copy_thread  scalar_processor_dmem
#define HIVE_ADDR_sp_raw_copy_thread 0xA8
#define HIVE_SIZE_sp_raw_copy_thread 4
#define HIVE_MEM_sp_input_v_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_input_v_addr 0xF3C
#define HIVE_SIZE_sp_input_v_addr 4
#define HIVE_MEM_dma_proxy_status  scalar_processor_dmem
#define HIVE_ADDR_dma_proxy_status 0xCC
#define HIVE_SIZE_dma_proxy_status 4
#define HIVE_MEM_sp_bin_copy_bytes_available  scalar_processor_dmem
#define HIVE_ADDR_sp_bin_copy_bytes_available 0x3914
#define HIVE_SIZE_sp_bin_copy_bytes_available 4
#define HIVE_MEM_sp_error  scalar_processor_dmem
#define HIVE_ADDR_sp_error 0x39C0
#define HIVE_SIZE_sp_error 4
#define HIVE_MEM_sp_read_sp_group_from_ddr  scalar_processor_dmem
#define HIVE_ADDR_sp_read_sp_group_from_ddr 0xF40
#define HIVE_SIZE_sp_read_sp_group_from_ddr 4
#define HIVE_MEM_sp_raw_copy_width  scalar_processor_dmem
#define HIVE_ADDR_sp_raw_copy_width 0x3990
#define HIVE_SIZE_sp_raw_copy_width 4
#define HIVE_MEM_sp_if_a  scalar_processor_dmem
#define HIVE_ADDR_sp_if_a 0x3928
#define HIVE_SIZE_sp_if_a 48
#define HIVE_MEM_sp_no_side_band  scalar_processor_dmem
#define HIVE_ADDR_sp_no_side_band 0xF44
#define HIVE_SIZE_sp_no_side_band 4
#define HIVE_MEM_sp_raw_copy_max_input_width  scalar_processor_dmem
#define HIVE_ADDR_sp_raw_copy_max_input_width 0x3994
#define HIVE_SIZE_sp_raw_copy_max_input_width 4
#define HIVE_MEM_sp_ch_id  scalar_processor_dmem
#define HIVE_ADDR_sp_ch_id 0xF48
#define HIVE_SIZE_sp_ch_id 4
#define HIVE_MEM_sp_sync_gen_vblank_cycles  scalar_processor_dmem
#define HIVE_ADDR_sp_sync_gen_vblank_cycles 0xF4C
#define HIVE_SIZE_sp_sync_gen_vblank_cycles 4
#define HIVE_MEM_sp_prbs_seed  scalar_processor_dmem
#define HIVE_ADDR_sp_prbs_seed 0xF50
#define HIVE_SIZE_sp_prbs_seed 4
#define HIVE_MEM_sp_tpg_x_mask  scalar_processor_dmem
#define HIVE_ADDR_sp_tpg_x_mask 0xF54
#define HIVE_SIZE_sp_tpg_x_mask 4
#define HIVE_MEM_xmem_bin_addr  scalar_processor_dmem
#define HIVE_ADDR_xmem_bin_addr 0xF58
#define HIVE_SIZE_xmem_bin_addr 4
#define HIVE_MEM_sp_fmt_type  scalar_processor_dmem
#define HIVE_ADDR_sp_fmt_type 0xF5C
#define HIVE_SIZE_sp_fmt_type 4
#define HIVE_MEM_sp_uds_config  scalar_processor_dmem
#define HIVE_ADDR_sp_uds_config 0x39B0
#define HIVE_SIZE_sp_uds_config 16
#define HIVE_MEM_sp_isp_started  scalar_processor_dmem
#define HIVE_ADDR_sp_isp_started 0xF60
#define HIVE_SIZE_sp_isp_started 4
#define HIVE_MEM_sp_obarea_start_bq  scalar_processor_dmem
#define HIVE_ADDR_sp_obarea_start_bq 0xF64
#define HIVE_SIZE_sp_obarea_start_bq 4
#define HIVE_MEM_sp_start_isp_thread  scalar_processor_dmem
#define HIVE_ADDR_sp_start_isp_thread 0x188
#define HIVE_SIZE_sp_start_isp_thread 4
#define HIVE_MEM_sp_proxy_thread  scalar_processor_dmem
#define HIVE_ADDR_sp_proxy_thread 0xD4
#define HIVE_SIZE_sp_proxy_thread 4
#define HIVE_MEM_sp_bin_copy_bytes_copied  scalar_processor_dmem
#define HIVE_ADDR_sp_bin_copy_bytes_copied 0x3918
#define HIVE_SIZE_sp_bin_copy_bytes_copied 4
#define HIVE_MEM_sp_raw_copy_height  scalar_processor_dmem
#define HIVE_ADDR_sp_raw_copy_height 0x3998
#define HIVE_SIZE_sp_raw_copy_height 4
#define HIVE_MEM_sp_raw_copy_out  scalar_processor_dmem
#define HIVE_ADDR_sp_raw_copy_out 0x399C
#define HIVE_SIZE_sp_raw_copy_out 4
#define HIVE_MEM_isp_sh_dma_cmd_buffer  scalar_processor_dmem
#define HIVE_ADDR_isp_sh_dma_cmd_buffer 0x39C4
#define HIVE_SIZE_isp_sh_dma_cmd_buffer 4
#define HIVE_MEM_sp_overlay_bg_u  scalar_processor_dmem
#define HIVE_ADDR_sp_overlay_bg_u 0xF68
#define HIVE_SIZE_sp_overlay_bg_u 4
#define HIVE_MEM_vf_pp_args  scalar_processor_dmem
#define HIVE_ADDR_vf_pp_args 0x3B20
#define HIVE_SIZE_vf_pp_args 76
#define HIVE_MEM_sp_sync_gen_width  scalar_processor_dmem
#define HIVE_ADDR_sp_sync_gen_width 0xF6C
#define HIVE_SIZE_sp_sync_gen_width 4
#define HIVE_ADDR_vf_pp_dynamic_entry 0x16C7
#define HIVE_MEM_current_thread  scalar_processor_dmem
#define HIVE_ADDR_current_thread 0x39A8
#define HIVE_SIZE_current_thread 4
#define HIVE_MEM_sp_dma_output_block_width_b  scalar_processor_dmem
#define HIVE_ADDR_sp_dma_output_block_width_b 0x3A08
#define HIVE_SIZE_sp_dma_output_block_width_b 4
#define HIVE_ADDR_sp_raw_copy_entry 0x486
#define HIVE_MEM_sp_tpg_x_delta  scalar_processor_dmem
#define HIVE_ADDR_sp_tpg_x_delta 0xF70
#define HIVE_SIZE_sp_tpg_x_delta 4
#define HIVE_ADDR_sp_init_dmem_entry 0x77
#define HIVE_MEM_sp_overlay_v_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_overlay_v_addr 0xF74
#define HIVE_SIZE_sp_overlay_v_addr 4
#define HIVE_MEM_sp_obarea_length_bq  scalar_processor_dmem
#define HIVE_ADDR_sp_obarea_length_bq 0xF78
#define HIVE_SIZE_sp_obarea_length_bq 4
#define HIVE_MEM_capture_pp_args  scalar_processor_dmem
#define HIVE_ADDR_capture_pp_args 0x3B6C
#define HIVE_SIZE_capture_pp_args 12
#define HIVE_MEM_vtmp4  scalar_processor_dmem
#define HIVE_ADDR_vtmp4 0xF7C
#define HIVE_SIZE_vtmp4 512
#define HIVE_MEM_sp_bin_copy_out  scalar_processor_dmem
#define HIVE_ADDR_sp_bin_copy_out 0x391C
#define HIVE_SIZE_sp_bin_copy_out 4
#define HIVE_MEM_sp_dma_crop_block_width_b  scalar_processor_dmem
#define HIVE_ADDR_sp_dma_crop_block_width_b 0x3A0C
#define HIVE_SIZE_sp_dma_crop_block_width_b 4
#define HIVE_MEM_sp_overlay_start_x  scalar_processor_dmem
#define HIVE_ADDR_sp_overlay_start_x 0x117C
#define HIVE_SIZE_sp_overlay_start_x 4
#define HIVE_MEM_sp_output_v_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_output_v_addr 0x1180
#define HIVE_SIZE_sp_output_v_addr 4
#define HIVE_ADDR_sp_start_isp_entry 0x0
#define HIVE_MEM_sp_no_dma_proxy  scalar_processor_dmem
#define HIVE_ADDR_sp_no_dma_proxy 0x440
#define HIVE_SIZE_sp_no_dma_proxy 4
#define HIVE_MEM_sp_raw_copy_padded_width  scalar_processor_dmem
#define HIVE_ADDR_sp_raw_copy_padded_width 0x39A0
#define HIVE_SIZE_sp_raw_copy_padded_width 4
#define HIVE_MEM_sp_current_isp_program  scalar_processor_dmem
#define HIVE_ADDR_sp_current_isp_program 0xF34
#define HIVE_SIZE_sp_current_isp_program 4
#define HIVE_MEM_sp_dma_crop_block_width_a  scalar_processor_dmem
#define HIVE_ADDR_sp_dma_crop_block_width_a 0x3A10
#define HIVE_SIZE_sp_dma_crop_block_width_a 4
#define HIVE_MEM_sp_dma_c_block_width_b  scalar_processor_dmem
#define HIVE_ADDR_sp_dma_c_block_width_b 0x3A14
#define HIVE_SIZE_sp_dma_c_block_width_b 4
#define HIVE_MEM_isp_vectors_per_line  scalar_processor_dmem
#define HIVE_ADDR_isp_vectors_per_line 0x1184
#define HIVE_SIZE_isp_vectors_per_line 4
#define HIVE_MEM_sp_ddr_data_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_ddr_data_addr 0x1188
#define HIVE_SIZE_sp_ddr_data_addr 4
#define HIVE_ADDR_sp_gen_histogram_entry 0x353
#define HIVE_MEM_sp_group  scalar_processor_dmem
#define HIVE_ADDR_sp_group 0x118C
#define HIVE_SIZE_sp_group 1160
#define HIVE_MEM_isp_uv_internal_width_vecs  scalar_processor_dmem
#define HIVE_ADDR_isp_uv_internal_width_vecs 0x1614
#define HIVE_SIZE_isp_uv_internal_width_vecs 4
#define HIVE_MEM_sp_input_y_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_input_y_addr 0x1618
#define HIVE_SIZE_sp_input_y_addr 4
#define HIVE_MEM_sp_dmem_data_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_dmem_data_addr 0x161C
#define HIVE_SIZE_sp_dmem_data_addr 4
#define HIVE_MEM_sp_sw_interrupt_value  scalar_processor_dmem
#define HIVE_ADDR_sp_sw_interrupt_value 0x1620
#define HIVE_SIZE_sp_sw_interrupt_value 4
#define HIVE_MEM_histogram_args  scalar_processor_dmem
#define HIVE_ADDR_histogram_args 0x3920
#define HIVE_SIZE_histogram_args 4
#define HIVE_MEM_sp_bss_size  scalar_processor_dmem
#define HIVE_ADDR_sp_bss_size 0x1624
#define HIVE_SIZE_sp_bss_size 4
#define HIVE_ADDR_capture_pp_dynamic_entry 0x37F7
#define HIVE_MEM_sp_tpg_y_delta  scalar_processor_dmem
#define HIVE_ADDR_sp_tpg_y_delta 0x1628
#define HIVE_SIZE_sp_tpg_y_delta 4
#define HIVE_MEM_sp_overlay_width  scalar_processor_dmem
#define HIVE_ADDR_sp_overlay_width 0x162C
#define HIVE_SIZE_sp_overlay_width 4
#define HIVE_MEM_isp_sdis_horiproj_num  scalar_processor_dmem
#define HIVE_ADDR_isp_sdis_horiproj_num 0x1630
#define HIVE_SIZE_isp_sdis_horiproj_num 4
#define HIVE_MEM_sp_dma_output_block_width_a  scalar_processor_dmem
#define HIVE_ADDR_sp_dma_output_block_width_a 0x3A18
#define HIVE_SIZE_sp_dma_output_block_width_a 4
#define HIVE_MEM_sp_input_mode  scalar_processor_dmem
#define HIVE_ADDR_sp_input_mode 0x1634
#define HIVE_SIZE_sp_input_mode 4
#define HIVE_MEM_sp_tpg_xy_mask  scalar_processor_dmem
#define HIVE_ADDR_sp_tpg_xy_mask 0x1638
#define HIVE_SIZE_sp_tpg_xy_mask 4
#define HIVE_MEM_sp_overlay_start_y  scalar_processor_dmem
#define HIVE_ADDR_sp_overlay_start_y 0x163C
#define HIVE_SIZE_sp_overlay_start_y 4
#define HIVE_MEM_sp_sp_group_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_sp_group_addr 0x1640
#define HIVE_SIZE_sp_sp_group_addr 4
#define HIVE_MEM_sp_data_size  scalar_processor_dmem
#define HIVE_ADDR_sp_data_size 0x1644
#define HIVE_SIZE_sp_data_size 4
#define HIVE_MEM_num_sp_threads  scalar_processor_dmem
#define HIVE_ADDR_num_sp_threads 0x39AC
#define HIVE_SIZE_num_sp_threads 4
#define HIVE_MEM_sp_output_y_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_output_y_addr 0x1648
#define HIVE_SIZE_sp_output_y_addr 4
#define HIVE_MEM_bayer_conf  scalar_processor_dmem
#define HIVE_ADDR_bayer_conf 0x18C
#define HIVE_SIZE_bayer_conf 56
#define HIVE_MEM_sp_proxy_busy_wait  scalar_processor_dmem
#define HIVE_ADDR_sp_proxy_busy_wait 0x528
#define HIVE_SIZE_sp_proxy_busy_wait 4
#define HIVE_MEM_sp_sync_gen_hblank_cycles  scalar_processor_dmem
#define HIVE_ADDR_sp_sync_gen_hblank_cycles 0x164C
#define HIVE_SIZE_sp_sync_gen_hblank_cycles 4
#define HIVE_MEM_isp_sdis_vertproj_num  scalar_processor_dmem
#define HIVE_ADDR_isp_sdis_vertproj_num 0x1650
#define HIVE_SIZE_isp_sdis_vertproj_num 4
#define HIVE_MEM_sp_sync_gen_height  scalar_processor_dmem
#define HIVE_ADDR_sp_sync_gen_height 0x1654
#define HIVE_SIZE_sp_sync_gen_height 4
#define HIVE_MEM_sp_program_input_circuit  scalar_processor_dmem
#define HIVE_ADDR_sp_program_input_circuit 0x1658
#define HIVE_SIZE_sp_program_input_circuit 4
#define HIVE_MEM_sp_if_b_changed  scalar_processor_dmem
#define HIVE_ADDR_sp_if_b_changed 0x3958
#define HIVE_SIZE_sp_if_b_changed 4
#define HIVE_MEM_sp_dma_c_block_width_a  scalar_processor_dmem
#define HIVE_ADDR_sp_dma_c_block_width_a 0x3A1C
#define HIVE_SIZE_sp_dma_c_block_width_a 4
#define HIVE_MEM_sp_dma_crop_cropping_a  scalar_processor_dmem
#define HIVE_ADDR_sp_dma_crop_cropping_a 0x3A20
#define HIVE_SIZE_sp_dma_crop_cropping_a 4
#define HIVE_MEM_sp_dma_output_skip_vecs  scalar_processor_dmem
#define HIVE_ADDR_sp_dma_output_skip_vecs 0x3A24
#define HIVE_SIZE_sp_dma_output_skip_vecs 4
#define HIVE_MEM_sp_vf_downscale_bits  scalar_processor_dmem
#define HIVE_ADDR_sp_vf_downscale_bits 0x165C
#define HIVE_SIZE_sp_vf_downscale_bits 4
#define HIVE_MEM_isp_sdis_vertcoef_vectors  scalar_processor_dmem
#define HIVE_ADDR_isp_sdis_vertcoef_vectors 0x1660
#define HIVE_SIZE_isp_sdis_vertcoef_vectors 4
#define HIVE_MEM_sp_overlay_bg_v  scalar_processor_dmem
#define HIVE_ADDR_sp_overlay_bg_v 0x1664
#define HIVE_SIZE_sp_overlay_bg_v 4
#define HIVE_MEM_sp_output_u_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_output_u_addr 0x1668
#define HIVE_SIZE_sp_output_u_addr 4
#define HIVE_MEM_output_dma_info_descr  scalar_processor_dmem
#define HIVE_ADDR_output_dma_info_descr 0x3AD8
#define HIVE_SIZE_output_dma_info_descr 72
#define HIVE_MEM_sp_isp_input_stream_format  scalar_processor_dmem
#define HIVE_ADDR_sp_isp_input_stream_format 0x166C
#define HIVE_SIZE_sp_isp_input_stream_format 4
#define HIVE_MEM_curr_binary_id  scalar_processor_dmem
#define HIVE_ADDR_curr_binary_id 0x0
#define HIVE_SIZE_curr_binary_id 4
#define HIVE_MEM_sp_dma_c_skip_vecs  scalar_processor_dmem
#define HIVE_ADDR_sp_dma_c_skip_vecs 0x3A28
#define HIVE_SIZE_sp_dma_c_skip_vecs 4
#define HIVE_MEM_sp_dma_vfout_cropping_a  scalar_processor_dmem
#define HIVE_ADDR_sp_dma_vfout_cropping_a 0x3A2C
#define HIVE_SIZE_sp_dma_vfout_cropping_a 4
#define HIVE_MEM_sp_overlay_bg_y  scalar_processor_dmem
#define HIVE_ADDR_sp_overlay_bg_y 0x1670
#define HIVE_SIZE_sp_overlay_bg_y 4
#define HIVE_MEM_sp_histo_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_histo_addr 0x3924
#define HIVE_SIZE_sp_histo_addr 4
#define HIVE_MEM_sp_overlay_u_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_overlay_u_addr 0x1674
#define HIVE_SIZE_sp_overlay_u_addr 4
#define HIVE_MEM_sp_input_u_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_input_u_addr 0x1678
#define HIVE_SIZE_sp_input_u_addr 4
#define HIVE_MEM_sp_tpg_y_mask  scalar_processor_dmem
#define HIVE_ADDR_sp_tpg_y_mask 0x167C
#define HIVE_SIZE_sp_tpg_y_mask 4
#define HIVE_MEM_sp_si  scalar_processor_dmem
#define HIVE_ADDR_sp_si 0x3A30
#define HIVE_SIZE_sp_si 68
#define HIVE_MEM_sp_debug  scalar_processor_dmem
#define HIVE_ADDR_sp_debug 0x39C8
#define HIVE_SIZE_sp_debug 64
#define HIVE_MEM_sp_raw_copy_raw_bit_depth  scalar_processor_dmem
#define HIVE_ADDR_sp_raw_copy_raw_bit_depth 0x39A4
#define HIVE_SIZE_sp_raw_copy_raw_bit_depth 4
#define HIVE_MEM_sp_overlay_y_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_overlay_y_addr 0x1680
#define HIVE_SIZE_sp_overlay_y_addr 4
#define HIVE_MEM_isp_sdis_horicoef_vectors  scalar_processor_dmem
#define HIVE_ADDR_isp_sdis_horicoef_vectors 0x1684
#define HIVE_SIZE_isp_sdis_horicoef_vectors 4
#define HIVE_MEM_sp_if_b  scalar_processor_dmem
#define HIVE_ADDR_sp_if_b 0x395C
#define HIVE_SIZE_sp_if_b 48
#define HIVE_MEM_sp_dmem_bss_addr  scalar_processor_dmem
#define HIVE_ADDR_sp_dmem_bss_addr 0x1688
#define HIVE_SIZE_sp_dmem_bss_addr 4
#define HIVE_MEM_sp_data  scalar_processor_dmem
#define HIVE_ADDR_sp_data 0x168C
#define HIVE_SIZE_sp_data 8704
#define HIVE_MEM_sp_overlay_height  scalar_processor_dmem
#define HIVE_ADDR_sp_overlay_height 0x388C
#define HIVE_SIZE_sp_overlay_height 4
#define HIVE_MEM_dma_proxy_kill_req  scalar_processor_dmem
#define HIVE_ADDR_dma_proxy_kill_req 0x524
#define HIVE_SIZE_dma_proxy_kill_req 1
#define HIVE_MEM_mem_map  scalar_processor_dmem
#define HIVE_ADDR_mem_map 0x3A74
#define HIVE_SIZE_mem_map 100
#define HIVE_MEM_sp_proxy_running  scalar_processor_dmem
#define HIVE_ADDR_sp_proxy_running 0x52C
#define HIVE_SIZE_sp_proxy_running 4
#define HIVE_MEM_sp_if_a_changed  scalar_processor_dmem
#define HIVE_ADDR_sp_if_a_changed 0x398C
#define HIVE_SIZE_sp_if_a_changed 4
#define HIVE_MEM_vtmp1  scalar_processor_dmem
#define HIVE_ADDR_vtmp1 0x3890
#define HIVE_SIZE_vtmp1 128
#define HIVE_MEM_isp_vf_output_width_vecs  scalar_processor_dmem
#define HIVE_ADDR_isp_vf_output_width_vecs 0x3910
#define HIVE_SIZE_isp_vf_output_width_vecs 4
#define HIVE_ADDR_sp_bin_copy_entry 0x2D8

#endif /* _SP_MAP_H_ */
