ccflags-y += -DATOMISP_POSTFIX=\"css2400b0_v2\" -DCONFIG_ISP2400B0 -DCONFIG_VIDEO_ATOMISP_CSS20
CONFIG_VIDEO_ATOMISP_CSS20 := m
CONFIG_ISP2400B0 := y
postfix := css2400b0_v2

include $(srctree)/$(src)/../Makefile.common
