# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_SWITCH_MID)	+= switch_mid.o
obj-$(CONFIG_SWITCH_MID_USER_NOTIFY)	+= switch_mid_user_notify.o

