snd-soc-sst-platform-objs := sst_platform.o
obj-$(CONFIG_SND_SST_PLATFORM) += snd-soc-sst-platform.o

# Medfield board
snd-soc-mfld-machine-objs := mfld_common.o mfld_machine.o
obj-$(CONFIG_SND_MFLD_MACHINE) += snd-soc-mfld-machine.o

# Gilligan Island/Lexington board
snd-soc-mfld-machine-gi-objs := mfld_common.o mfld_machine_gi.o
obj-$(CONFIG_SND_MFLD_MACHINE_GI) += snd-soc-mfld-machine-gi.o

# Cloverview/Clovertrail+ board
snd-soc-clv-machine-objs := clv_machine.o
obj-$(CONFIG_SND_CLV_MACHINE) += snd-soc-clv-machine.o

# SST Compress framework driver
snd-compress-sst-objs := compress_sst.o
obj-$(CONFIG_SND_COMPRESS_SST) += snd-compress-sst.o

# Merrfield board
snd-soc-mrfld-machine-objs := mrfld_machine.o
obj-$(CONFIG_SND_MRFLD_MACHINE) += snd-soc-mrfld-machine.o

# DSP driver
obj-$(CONFIG_SND_INTEL_SST) += sst/

# Audio Comms
snd-soc-comms-machine-objs := mfld_comms_machine.o
snd-soc-ssp-objs := mfld_ssp.o
obj-$(CONFIG_SND_MFLD_COMMS_MACHINE) += mfld_comms_machine.o
obj-$(CONFIG_SND_SOC_SSP) += mid_ssp.o
