snd-soc-sst-platform-objs := sst_platform.o
obj-$(CONFIG_SND_SST_PLATFORM) += snd-soc-sst-platform.o

# Medfield board
snd-soc-mfld-machine-objs := mfld_common.o mfld_machine.o
obj-$(CONFIG_SND_MFLD_MACHINE) += snd-soc-mfld-machine.o

# Gilligan Island/Lexington board
snd-soc-mfld-machine-gi-objs := mfld_common.o mfld_machine_gi.o
obj-$(CONFIG_SND_MFLD_MACHINE_GI) += snd-soc-mfld-machine-gi.o

# Cloverview/Clovertrail+ board
snd-soc-clv-machine-objs := clv_machine.o
obj-$(CONFIG_SND_CLV_MACHINE) += snd-soc-clv-machine.o

# DSP driver
