# platform configuration for board devices
obj-y += device_libs/

# INTEL-MID specific files
obj-$(CONFIG_X86_INTEL_MID) += intel_mid_vrtc.o
obj-$(CONFIG_EARLY_PRINTK_INTEL_MID) += early_printk_intel_mid.o
obj-$(CONFIG_X86_INTEL_MID) += intel-mid.o
# MFLD specific files
obj-$(CONFIG_X86_MDFLD) += mfld.o
# BOARD files
obj-$(CONFIG_BOARD_MFLD_BLACKBAY) += board-blackbay.o
