#
# Makefile for sensor chip drivers.
#

obj-$(CONFIG_THERMAL)			+= thermal_sys.o
obj-$(CONFIG_SPEAR_THERMAL)		+= spear_thermal.o
obj-$(CONFIG_SENSORS_THERMAL_MRFLD)	+= intel_mrfl_thermal.o
obj-$(CONFIG_INTEL_BYT_THERMAL)		+= intel_byt_thermal.o
obj-$(CONFIG_SOC_THERMAL)		+= intel_soc_thermal.o
