ccflags-y += -DATOMISP_POSTFIX=\"css2300\" -DCONFIG_ISP2300 -DCONFIG_VIDEO_ATOMISP_CSS15
CONFIG_VIDEO_ATOMISP_CSS15 := m
CONFIG_ISP2300 := y
postfix := css2300

include $(srctree)/$(src)/../Makefile.common
