#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
#ccflags-y += -DDEBUG
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_RMI4_I2C)	+=  rmi_bus.o rmi_sensor.o rmi_function.o rmi_f01.o rmi_f05.o rmi_f11.o rmi_f19.o rmi_f34.o rmi_f54.o rmi_i2c.o
