#
# Makefile for HSI clients
#

CFLAGS_hsi_ffl_tty.o := -DDEBUG

obj-$(CONFIG_SSI_PROTOCOL)	+= ssi_protocol.o
obj-$(CONFIG_HSI_CHAR)		+= hsi_char.o
obj-$(CONFIG_HSI_CMT_SPEECH)	+= cmt_speech.o
obj-$(CONFIG_HSI_FFL_TTY)	+= hsi_ffl_tty.o

